# Insurance data analysis #

In [2]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\map\\insurance\\hover\\country\\india\\state\\"
map_state_list=os.listdir(path)
map_state_list

clm={'state':[], 'year':[],'quarter':[],'region_name':[], 'transaction_count':[], 'transaction_amount':[]}

for i in map_state_list:
    p_i=path+i+"\\"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"\\"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for m in D['data']['hoverDataList']:
                name = m['name']
                for n in m['metric']:
                    count = n['count']
                    amount = n['amount']
                    clm['region_name'].append(name)
                    clm['transaction_count'].append(count)
                    clm['transaction_amount'].append(amount)
                    clm['state'].append(i)
                    clm['year'].append(j)
                    clm['quarter'].append(int(k.strip('.json')))


map_insurance_df=pd.DataFrame(clm)

In [3]:
map_insurance_df

,state,year,quarter,region_name,transaction_count,transaction_amount
0,andaman-&-nicobar-islands,2020,2,south andaman district,3,795.0
1,andaman-&-nicobar-islands,2020,2,nicobars district,3,565.0
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1,281.0
3,andaman-&-nicobar-islands,2020,3,south andaman district,35,13651.0
4,andaman-&-nicobar-islands,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,west-bengal,2024,4,alipurduar district,1023,1613143.0
13872,west-bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,west-bengal,2024,4,nadia district,3807,5031294.0
13874,west-bengal,2024,4,birbhum district,1818,2423290.0
13875,west-bengal,2024,4,purba medinipur district,3559,4439061.0

In [4]:
map_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13876 entries, 0 to 13875
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               13876 non-null  str
 1   year                13876 non-null  str
 2   quarter             13876 non-null  int64
 3   region_name         13876 non-null  str
 4   transaction_count   13876 non-null  int64
 5   transaction_amount  13876 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.1 MB

In [5]:
map_insurance_df.shape

(13876, 6)

In [6]:
map_insurance_df[(map_insurance_df['quarter'] == 1) & (map_insurance_df['state'] == 'andaman-&-nicobar-islands')]

,state,year,quarter,region_name,transaction_count,transaction_amount
8,andaman-&-nicobar-islands,2021,1,north and middle andaman district,48,63978.0
9,andaman-&-nicobar-islands,2021,1,south andaman district,164,167044.0
10,andaman-&-nicobar-islands,2021,1,nicobars district,13,13244.0
20,andaman-&-nicobar-islands,2022,1,north and middle andaman district,48,85229.0
21,andaman-&-nicobar-islands,2022,1,south andaman district,692,982206.0
22,andaman-&-nicobar-islands,2022,1,nicobars district,28,63852.0
32,andaman-&-nicobar-islands,2023,1,north and middle andaman district,85,178969.0
33,andaman-&-nicobar-islands,2023,1,south andaman district,872,1172083.0
34,andaman-&-nicobar-islands,2023,1,nicobars district,47,88146.0
44,andaman-&-nicobar-islands,2024,1,north and middle andaman district,125,229226.0
45,andaman-&-nicobar-islands,2024,1,south andaman district,1190,1657627.0
46,andaman-&-nicobar-islands,2024,1,nicobars district,56,77703.0

In [7]:
map_insurance_df[(map_insurance_df['quarter'] == 1) & (map_insurance_df['state'] == 'andaman-&-nicobar-islands')].shape

(12, 6)

In [8]:
map_insurance_df.describe()

            quarter  transaction_count  transaction_amount
count  13876.000000       13876.000000        1.387600e+04
mean       2.586841        1046.100245        1.442460e+06
std        1.092294        3131.642623        4.503385e+06
min        1.000000           1.000000        3.100000e+01
25%        2.000000         113.000000        1.050938e+05
50%        3.000000         332.000000        4.414915e+05
75%        4.000000         909.000000        1.280078e+06
max        4.000000       96935.000000        1.592248e+08

In [9]:
map_insurance_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [10]:
map_insurance_df.isna().sum()

state                 0
year                  0
quarter               0
region_name           0
transaction_count     0
transaction_amount    0
dtype: int64

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [11]:
map_insurance_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [12]:
map_insurance_df['state'].value_counts()

state
uttar-pradesh                         1427
madhya-pradesh                         994
bihar                                  722
tamil-nadu                             707
maharashtra                            684
rajasthan                              662
assam                                  631
gujarat                                628
telangana                              628
karnataka                              574
odisha                                 572
chhattisgarh                           525
jharkhand                              457
west-bengal                            439
punjab                                 420
haryana                                418
arunachal-pradesh                      415
jammu-&-kashmir                        405
andhra-pradesh                         275
kerala                                 267
manipur                                264
uttarakhand                            247
himachal-pradesh                       227
delhi                                  210
meghalaya                              200
nagaland                               197
tripura                                152
mizoram                                148
sikkim                                  79
puducherry                              76
andaman-&-nicobar-islands               57
dadra-&-nagar-haveli-&-daman-&-diu      57
goa                                     38
ladakh                                  38
chandigarh                              19
lakshadweep                             17
Name: count, dtype: int64

In [13]:
map_insurance_df['state'] = map_insurance_df['state'].str.strip().str.title()

In [14]:
map_insurance_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Region name Column Unique Values ##

In [15]:
map_insurance_df['region_name'].unique()

<ArrowStringArray>
[           'south andaman district',                 'nicobars district',
 'north and middle andaman district',                  'nicobar district',
            'east godavari district',               'srikakulam district',
             'spsr nellore district',             'vizianagaram district',
            'visakhapatnam district',                 'prakasam district',
 ...
               'alipurduar district',        'paschim bardhaman district',
                    'nadia district',                  'birbhum district',
          'purba medinipur district',                   'maldah district',
                'darjiling district',               'darjeeling district',
              'cooch behar district',                    'malda district']
Length: 842, dtype: str

In [16]:
map_insurance_df['region_name'] = map_insurance_df['region_name'].str.strip().str.title()

In [17]:
map_insurance_df['region_name'].unique()

<ArrowStringArray>
[           'South Andaman District',                 'Nicobars District',
 'North And Middle Andaman District',                  'Nicobar District',
            'East Godavari District',               'Srikakulam District',
             'Spsr Nellore District',             'Vizianagaram District',
            'Visakhapatnam District',                 'Prakasam District',
 ...
               'Alipurduar District',        'Paschim Bardhaman District',
                    'Nadia District',                  'Birbhum District',
          'Purba Medinipur District',                   'Maldah District',
                'Darjiling District',               'Darjeeling District',
              'Cooch Behar District',                    'Malda District']
Length: 842, dtype: str

In [18]:
map_insurance_df

,state,year,quarter,region_name,transaction_count,transaction_amount
0,Andaman-&-Nicobar-Islands,2020,2,South Andaman District,3,795.0
1,Andaman-&-Nicobar-Islands,2020,2,Nicobars District,3,565.0
2,Andaman-&-Nicobar-Islands,2020,3,North And Middle Andaman District,1,281.0
3,Andaman-&-Nicobar-Islands,2020,3,South Andaman District,35,13651.0
4,Andaman-&-Nicobar-Islands,2020,3,Nicobars District,5,1448.0
...,...,...,...,...,...,...
13871,West-Bengal,2024,4,Alipurduar District,1023,1613143.0
13872,West-Bengal,2024,4,Paschim Bardhaman District,4945,7005851.0
13873,West-Bengal,2024,4,Nadia District,3807,5031294.0
13874,West-Bengal,2024,4,Birbhum District,1818,2423290.0
13875,West-Bengal,2024,4,Purba Medinipur District,3559,4439061.0

## VALIDATE FINAL DATASET INTEGRITY ##

In [19]:
map_insurance_df.shape

(13876, 6)

In [20]:
map_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13876 entries, 0 to 13875
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               13876 non-null  str
 1   year                13876 non-null  str
 2   quarter             13876 non-null  int64
 3   region_name         13876 non-null  str
 4   transaction_count   13876 non-null  int64
 5   transaction_amount  13876 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.1 MB

In [22]:
map_insurance_df['quarter'].unique()

array([2, 3, 4, 1])

In [23]:
map_insurance_df['region_name'] = map_insurance_df['region_name'].astype('category')

In [24]:
map_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13876 entries, 0 to 13875
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               13876 non-null  str
 1   year                13876 non-null  str
 2   quarter             13876 non-null  int64
 3   region_name         13876 non-null  category
 4   transaction_count   13876 non-null  int64
 5   transaction_amount  13876 non-null  float64
dtypes: category(1), float64(1), int64(2), str(2)
memory usage: 781.1 KB

In [25]:
map_insurance_df['year'] = map_insurance_df['year'].astype('int32')

In [26]:
map_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13876 entries, 0 to 13875
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               13876 non-null  str
 1   year                13876 non-null  int32
 2   quarter             13876 non-null  int64
 3   region_name         13876 non-null  category
 4   transaction_count   13876 non-null  int64
 5   transaction_amount  13876 non-null  float64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 672.7 KB

## Create Map_Insurance Table In Database ##

In [27]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS map_insurance (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER,
        region_name VARCHAR(255),
        transaction_count BIGINT,
        transaction_amount NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.map_insurance')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'map_insurance' created successfully")

Table exists in PostgreSQL: map_insurance
Table 'map_insurance' created successfully

## Inserting Data from Data Frame to Transaction_data Table ##

In [29]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in map_insurance_df.iterrows():
    cur.execute(
        """
        INSERT INTO insurance_map (
            state,
            year,
            quarter,
            region_name,
            transaction_count,
            transaction_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["region_name"],
            row["transaction_count"],
            row["transaction_amount"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully

In [28]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()
cur.execute("""ALTER TABLE map_insurance
RENAME TO insurance_map;""")


conn.commit()
cur.close()
conn.close()
print("Table name changed to transaction_map successfully")

Table name changed to transaction_map successfully