# Top Transaction Districts data analysis #

In [3]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\top\\transaction\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
clm={'state':[], 'year':[],'quarter':[],'districts':[], 'total_amount':[], 'total_count':[] }

for i in top_state_list:
    p_i=path+i+"\\"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"\\"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['districts']:
                districts = z['entityName']
                total_amount = z['metric']['amount']
                total_count = z['metric']['count']
                clm['districts'].append(districts)
                clm['total_amount'].append(total_amount)
                clm['total_count'].append(total_count)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

top_transactions_districts_df=pd.DataFrame(clm)

top_transactions_districts_df

,state,year,quarter,districts,total_amount,total_count
0,andaman-&-nicobar-islands,2018,1,south andaman,1.256025e+07,5688
1,andaman-&-nicobar-islands,2018,1,nicobars,1.139849e+06,528
2,andaman-&-nicobar-islands,2018,1,north and middle andaman,9.316631e+05,442
3,andaman-&-nicobar-islands,2018,2,south andaman,2.394824e+07,9395
4,andaman-&-nicobar-islands,2018,2,nicobars,3.072437e+06,1120
...,...,...,...,...,...,...
8291,west-bengal,2024,4,howrah,1.025764e+11,67496284
8292,west-bengal,2024,4,nadia,1.079320e+11,65274337
8293,west-bengal,2024,4,malda,1.024212e+11,63424613
8294,west-bengal,2024,4,hooghly,9.071383e+10,59676576
8295,west-bengal,2024,4,paschim medinipur,8.431774e+10,58238212

In [4]:
top_transactions_districts_df.shape

(8296, 6)

In [5]:
top_transactions_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         8296 non-null   str
 1   year          8296 non-null   str
 2   quarter       8296 non-null   int64
 3   districts     8296 non-null   str
 4   total_amount  8296 non-null   float64
 5   total_count   8296 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 571.1 KB

In [6]:
q2_andaman = top_transactions_districts_df[
    (top_transactions_districts_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (top_transactions_districts_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'districts', 'total_amount', 'total_count']])

    year  quarter                 districts  total_amount  total_count
3   2018        2             south andaman  2.394824e+07         9395
4   2018        2                  nicobars  3.072437e+06         1120
5   2018        2  north and middle andaman  1.317863e+06          825
15  2019        2             south andaman  1.025310e+08        28490
16  2019        2  north and middle andaman  8.612103e+06         3371
17  2019        2                  nicobars  9.111651e+06         1828
27  2020        2             south andaman  1.328558e+08        48088
28  2020        2  north and middle andaman  2.244771e+07        10979
29  2020        2                  nicobars  1.434151e+07         3895
39  2021        2             south andaman  7.608930e+08       286907
40  2021        2  north and middle andaman  9.023339e+07        39200
41  2021        2                  nicobars  4.802061e+07        15307
51  2022        2             south andaman  2.357327e+09       954875
52  2022        2  north and middle andaman  1.956932e+08        72573
53  2022        2                  nicobars  1.329006e+08        43769
63  2023        2             south andaman  4.297737e+09      2417058
64  2023        2  north and middle andaman  4.624147e+08       181149
65  2023        2                  nicobars  2.301924e+08       109568
75  2024        2             south andaman  6.285248e+09      4153251
76  2024        2  north and middle andaman  6.768449e+08       313301
77  2024        2                  nicobars  3.336874e+08       186672

In [7]:
top_transactions_districts_df.describe()

           quarter  total_amount   total_count
count  8296.000000  8.296000e+03  8.296000e+03
mean      2.500964  2.918812e+10  2.052930e+07
std       1.118101  8.585430e+10  6.948810e+07
min       1.000000  5.471802e+05  4.420000e+02
25%       2.000000  5.229769e+08  2.865748e+05
50%       3.000000  3.948058e+09  2.341064e+06
75%       4.000000  2.491626e+10  1.492785e+07
max       4.000000  1.790144e+12  1.674348e+09

In [8]:
top_transactions_districts_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [9]:
top_transactions_districts_df.isna().sum()

state           0
year            0
quarter         0
districts       0
total_amount    0
total_count     0
dtype: int64

In [10]:
top_transactions_districts_df['districts'].isna().sum()

np.int64(0)

In [11]:
top_transactions_districts_df['districts']

0                  south andaman
1                       nicobars
2       north and middle andaman
3                  south andaman
4                       nicobars
                  ...
8291                      howrah
8292                       nadia
8293                       malda
8294                     hooghly
8295           paschim medinipur
Name: districts, Length: 8296, dtype: str

In [12]:
top_transactions_districts_df[top_transactions_districts_df['districts'].isna()]

Empty DataFrame
Columns: [state, year, quarter, districts, total_amount, total_count]
Index: []

In [13]:
top_transactions_districts_df[top_transactions_districts_df['districts'].isna()]

Empty DataFrame
Columns: [state, year, quarter, districts, total_amount, total_count]
Index: []

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [14]:
top_transactions_districts_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [15]:
top_transactions_districts_df['state'].value_counts()

state
andhra-pradesh                        280
arunachal-pradesh                     280
assam                                 280
bihar                                 280
chhattisgarh                          280
delhi                                 280
gujarat                               280
haryana                               280
himachal-pradesh                      280
jammu-&-kashmir                       280
jharkhand                             280
karnataka                             280
kerala                                280
madhya-pradesh                        280
maharashtra                           280
manipur                               280
meghalaya                             280
nagaland                              280
odisha                                280
punjab                                280
rajasthan                             280
tamil-nadu                            280
telangana                             280
uttar-pradesh                         280
uttarakhand                           280
west-bengal                           280
mizoram                               228
tripura                               224
sikkim                                116
puducherry                            112
andaman-&-nicobar-islands              84
dadra-&-nagar-haveli-&-daman-&-diu     84
goa                                    56
ladakh                                 56
chandigarh                             28
lakshadweep                            28
Name: count, dtype: int64

In [16]:
top_transactions_districts_df['state'] = top_transactions_districts_df['state'].str.strip().str.title()

In [17]:
top_transactions_districts_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Districts Column Unique Values ##

In [18]:
top_transactions_districts_df['districts'].unique()

<ArrowStringArray>
[             'south andaman',                   'nicobars',
   'north and middle andaman',                    'nicobar',
              'visakhapatnam',              'east godavari',
                    'krishna',                   'chittoor',
                     'guntur',                    'kurnool',
 ...
                     'maldah', 'south twenty four parganas',
          'paschim medinipur',            'purba bardhaman',
                    'bankura',          'paschim bardhaman',
                    'purulia',                    'hooghly',
                     'howrah',                      'malda']
Length: 409, dtype: str

In [19]:
top_transactions_districts_df[top_transactions_districts_df['districts'] == 'nicobar']

,state,year,quarter,districts,total_amount,total_count
80,Andaman-&-Nicobar-Islands,2024,3,nicobar,372462759.0,210536
83,Andaman-&-Nicobar-Islands,2024,4,nicobar,401676455.0,232820

In [20]:
top_transactions_districts_df['districts'] = top_transactions_districts_df['districts'].replace('nicobar', 'nicobars')

In [21]:
top_transactions_districts_df[top_transactions_districts_df['districts'] == 'nicobars']

,state,year,quarter,districts,total_amount,total_count
1,Andaman-&-Nicobar-Islands,2018,1,nicobars,1.139849e+06,528
4,Andaman-&-Nicobar-Islands,2018,2,nicobars,3.072437e+06,1120
7,Andaman-&-Nicobar-Islands,2018,3,nicobars,6.387829e+06,1471
11,Andaman-&-Nicobar-Islands,2018,4,nicobars,7.180859e+06,1485
14,Andaman-&-Nicobar-Islands,2019,1,nicobars,7.236060e+06,1539
17,Andaman-&-Nicobar-Islands,2019,2,nicobars,9.111651e+06,1828
20,Andaman-&-Nicobar-Islands,2019,3,nicobars,1.156642e+07,2300
23,Andaman-&-Nicobar-Islands,2019,4,nicobars,1.238416e+07,2600
26,Andaman-&-Nicobar-Islands,2020,1,nicobars,1.209954e+07,2911
29,Andaman-&-Nicobar-Islands,2020,2,nicobars,1.434151e+07,3895
32,Andaman-&-Nicobar-Islands,2020,3,nicobars,2.216645e+07,5413
35,Andaman-&-Nicobar-Islands,2020,4,nicobars,3.521887e+07,8688
38,Andaman-&-Nicobar-Islands,2021,1,nicobars,3.907527e+07,10302
41,Andaman-&-Nicobar-Islands,2021,2,nicobars,4.802061e+07,15307
44,Andaman-&-Nicobar-Islands,2021,3,nicobars,7.498052e+07,20754
47,Andaman-&-Nicobar-Islands,2021,4,nicobars,8.132928e+07,24437
50,Andaman-&-Nicobar-Islands,2022,1,nicobars,9.441413e+07,29177
53,Andaman-&-Nicobar-Islands,2022,2,nicobars,1.329006e+08,43769
56,Andaman-&-Nicobar-Islands,2022,3,nicobars,1.313304e+08,49550
59,Andaman-&-Nicobar-Islands,2022,4,nicobars,1.423559e+08,58646
62,Andaman-&-Nicobar-Islands,2023,1,nicobars,2.020628e+08,94127
65,Andaman-&-Nicobar-Islands,2023,2,nicobars,2.301924e+08,109568
68,Andaman-&-Nicobar-Islands,2023,3,nicobars,2.537722e+08,128432
71,Andaman-&-Nicobar-Islands,2023,4,nicobars,3.115279e+08,153587
74,Andaman-&-Nicobar-Islands,2024,1,nicobars,3.053463e+08,166796
77,Andaman-&-Nicobar-Islands,2024,2,nicobars,3.336874e+08,186672
80,Andaman-&-Nicobar-Islands,2024,3,nicobars,3.724628e+08,210536
83,Andaman-&-Nicobar-Islands,2024,4,nicobars,4.016765e+08,232820

In [22]:
top_transactions_districts_df['districts'].unique()

<ArrowStringArray>
[             'south andaman',                   'nicobars',
   'north and middle andaman',              'visakhapatnam',
              'east godavari',                    'krishna',
                   'chittoor',                     'guntur',
                    'kurnool',                  'anantapur',
 ...
                     'maldah', 'south twenty four parganas',
          'paschim medinipur',            'purba bardhaman',
                    'bankura',          'paschim bardhaman',
                    'purulia',                    'hooghly',
                     'howrah',                      'malda']
Length: 408, dtype: str

## VALIDATE FINAL DATASET INTEGRITY ##

In [23]:
top_transactions_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         8296 non-null   str
 1   year          8296 non-null   str
 2   quarter       8296 non-null   int64
 3   districts     8296 non-null   str
 4   total_amount  8296 non-null   float64
 5   total_count   8296 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 572.1 KB

In [24]:
top_transactions_districts_df['year'] = top_transactions_districts_df['year'].astype('int32')
top_transactions_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         8296 non-null   str
 1   year          8296 non-null   int32
 2   quarter       8296 non-null   int64
 3   districts     8296 non-null   str
 4   total_amount  8296 non-null   float64
 5   total_count   8296 non-null   int64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 507.3 KB

In [25]:
top_transactions_districts_df

,state,year,quarter,districts,total_amount,total_count
0,Andaman-&-Nicobar-Islands,2018,1,south andaman,1.256025e+07,5688
1,Andaman-&-Nicobar-Islands,2018,1,nicobars,1.139849e+06,528
2,Andaman-&-Nicobar-Islands,2018,1,north and middle andaman,9.316631e+05,442
3,Andaman-&-Nicobar-Islands,2018,2,south andaman,2.394824e+07,9395
4,Andaman-&-Nicobar-Islands,2018,2,nicobars,3.072437e+06,1120
...,...,...,...,...,...,...
8291,West-Bengal,2024,4,howrah,1.025764e+11,67496284
8292,West-Bengal,2024,4,nadia,1.079320e+11,65274337
8293,West-Bengal,2024,4,malda,1.024212e+11,63424613
8294,West-Bengal,2024,4,hooghly,9.071383e+10,59676576
8295,West-Bengal,2024,4,paschim medinipur,8.431774e+10,58238212

In [26]:
top_transactions_districts_df

,state,year,quarter,districts,total_amount,total_count
0,Andaman-&-Nicobar-Islands,2018,1,south andaman,1.256025e+07,5688
1,Andaman-&-Nicobar-Islands,2018,1,nicobars,1.139849e+06,528
2,Andaman-&-Nicobar-Islands,2018,1,north and middle andaman,9.316631e+05,442
3,Andaman-&-Nicobar-Islands,2018,2,south andaman,2.394824e+07,9395
4,Andaman-&-Nicobar-Islands,2018,2,nicobars,3.072437e+06,1120
...,...,...,...,...,...,...
8291,West-Bengal,2024,4,howrah,1.025764e+11,67496284
8292,West-Bengal,2024,4,nadia,1.079320e+11,65274337
8293,West-Bengal,2024,4,malda,1.024212e+11,63424613
8294,West-Bengal,2024,4,hooghly,9.071383e+10,59676576
8295,West-Bengal,2024,4,paschim medinipur,8.431774e+10,58238212

In [27]:
top_transactions_districts_df['districts'] = top_transactions_districts_df['districts'].str.strip().str.title()

In [28]:
top_transactions_districts_df['districts']

0                  South Andaman
1                       Nicobars
2       North And Middle Andaman
3                  South Andaman
4                       Nicobars
                  ...
8291                      Howrah
8292                       Nadia
8293                       Malda
8294                     Hooghly
8295           Paschim Medinipur
Name: districts, Length: 8296, dtype: str

In [29]:
top_transactions_districts_df

,state,year,quarter,districts,total_amount,total_count
0,Andaman-&-Nicobar-Islands,2018,1,South Andaman,1.256025e+07,5688
1,Andaman-&-Nicobar-Islands,2018,1,Nicobars,1.139849e+06,528
2,Andaman-&-Nicobar-Islands,2018,1,North And Middle Andaman,9.316631e+05,442
3,Andaman-&-Nicobar-Islands,2018,2,South Andaman,2.394824e+07,9395
4,Andaman-&-Nicobar-Islands,2018,2,Nicobars,3.072437e+06,1120
...,...,...,...,...,...,...
8291,West-Bengal,2024,4,Howrah,1.025764e+11,67496284
8292,West-Bengal,2024,4,Nadia,1.079320e+11,65274337
8293,West-Bengal,2024,4,Malda,1.024212e+11,63424613
8294,West-Bengal,2024,4,Hooghly,9.071383e+10,59676576
8295,West-Bengal,2024,4,Paschim Medinipur,8.431774e+10,58238212

In [30]:
top_transactions_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         8296 non-null   str
 1   year          8296 non-null   int32
 2   quarter       8296 non-null   int64
 3   districts     8296 non-null   str
 4   total_amount  8296 non-null   float64
 5   total_count   8296 non-null   int64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 508.3 KB

In [31]:
top_transactions_districts_df['districts'].unique()

<ArrowStringArray>
[             'South Andaman',                   'Nicobars',
   'North And Middle Andaman',              'Visakhapatnam',
              'East Godavari',                    'Krishna',
                   'Chittoor',                     'Guntur',
                    'Kurnool',                  'Anantapur',
 ...
                     'Maldah', 'South Twenty Four Parganas',
          'Paschim Medinipur',            'Purba Bardhaman',
                    'Bankura',          'Paschim Bardhaman',
                    'Purulia',                    'Hooghly',
                     'Howrah',                      'Malda']
Length: 408, dtype: str

In [32]:
top_transactions_districts_df['districts'] = top_transactions_districts_df['districts'].astype('category')

In [33]:
top_transactions_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         8296 non-null   str
 1   year          8296 non-null   int32
 2   quarter       8296 non-null   int64
 3   districts     8296 non-null   category
 4   total_amount  8296 non-null   float64
 5   total_count   8296 non-null   int64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 395.1 KB

## Create users_district_top Table In Database ##

In [37]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS transaction_districts_top (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,
        districts VARCHAR(255) NOT NULL,
        total_count BIGINT,
        total_amount NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.transaction_districts_top')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'transaction_districts_top' created successfully")

Table exists in PostgreSQL: transaction_districts_top
Table 'transaction_districts_top' created successfully

## Inserting Data from Data Frame to Transaction_district_Top Table ##

In [38]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in top_transactions_districts_df.iterrows():
    cur.execute(
        """
        INSERT INTO transaction_districts_top (
            state,
            year,
            quarter,
            districts,
            total_count,
            total_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["districts"],
            row["total_count"],
            row["total_amount"],
        )
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully
Data inserted successfully