# Top Transactions Pincodes data analysis #

In [3]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\top\\transaction\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
clm={'state':[], 'year':[],'quarter':[],'pincodes':[], 'transactions_count':[], 'transactions_amount':[] }

for i in top_state_list:
    p_i=path+i+"\\"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"\\"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['pincodes']:
                pincodes = z['entityName']
                transactions_count=z['metric']['count']
                transactions_amount=z['metric']['amount']
                clm['pincodes'].append(pincodes)
                clm['transactions_count'].append(transactions_count)
                clm['transactions_amount'].append(transactions_amount)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

top_transactions_pincodes_df=pd.DataFrame(clm)

top_transactions_pincodes_df

,state,year,quarter,pincodes,transactions_count,transactions_amount
0,andaman-&-nicobar-islands,2018,1,744101,1622,2.769298e+06
1,andaman-&-nicobar-islands,2018,1,744103,1223,2.238042e+06
2,andaman-&-nicobar-islands,2018,1,744102,969,3.519060e+06
3,andaman-&-nicobar-islands,2018,1,744105,685,1.298561e+06
4,andaman-&-nicobar-islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,west-bengal,2024,4,711101,6753348,1.049483e+10
9995,west-bengal,2024,4,700059,6662715,8.009476e+09
9996,west-bengal,2024,4,700039,6575693,9.018748e+09
9997,west-bengal,2024,4,734001,6432082,8.996529e+09
9998,west-bengal,2024,4,733134,6313560,1.050259e+10

In [6]:
len(D['data']['pincodes'])

10

In [10]:
len(top_transactions_pincodes_df['pincodes'])

9999

In [11]:
top_transactions_pincodes_df.shape

(9999, 6)

In [13]:
top_transactions_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                9999 non-null   str
 1   year                 9999 non-null   str
 2   quarter              9999 non-null   int64
 3   pincodes             9997 non-null   str
 4   transactions_count   9999 non-null   int64
 5   transactions_amount  9999 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 667.4 KB

In [14]:
q2_andaman = top_transactions_pincodes_df[
    (top_transactions_pincodes_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (top_transactions_pincodes_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'pincodes', 'transactions_amount']])

     year  quarter pincodes  transactions_amount
10   2018        2   744101         6.310090e+06
11   2018        2   744103         4.752147e+06
12   2018        2   744102         5.810268e+06
13   2018        2   744105         2.200333e+06
14   2018        2   744301         1.953749e+06
..    ...      ...      ...                  ...
255  2024        2   744107         2.791837e+08
256  2024        2   744104         2.884798e+08
257  2024        2   744112         2.127500e+08
258  2024        2   744202         3.096408e+08
259  2024        2   744301         1.921164e+08

[70 rows x 4 columns]

In [15]:
top_transactions_pincodes_df.describe()

           quarter  transactions_count  transactions_amount
count  9999.000000        9.999000e+03         9.999000e+03
mean      2.500550        4.877050e+06         6.712874e+09
std       1.118045        1.969986e+07         2.940946e+10
min       1.000000        2.000000e+00         6.025276e+01
25%       2.000000        6.977400e+04         1.401156e+08
50%       3.000000        5.120020e+05         7.895725e+08
75%       4.000000        3.241928e+06         4.687477e+09
max       4.000000        9.675084e+08         1.501500e+12

In [16]:
top_transactions_pincodes_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [17]:
top_transactions_pincodes_df.isna().sum()

state                  0
year                   0
quarter                0
pincodes               2
transactions_count     0
transactions_amount    0
dtype: int64

In [18]:
top_transactions_pincodes_df['pincodes'].isna().sum()

np.int64(2)

In [19]:
top_transactions_pincodes_df['pincodes']

0       744101
1       744103
2       744102
3       744105
4       744104
         ...
9994    711101
9995    700059
9996    700039
9997    734001
9998    733134
Name: pincodes, Length: 9999, dtype: str

In [20]:
top_transactions_pincodes_df[top_transactions_pincodes_df['pincodes'].isna()]

       state  year  quarter pincodes  transactions_count  transactions_amount
4810  ladakh  2019        4      NaN                2014         1.009866e+07
4852  ladakh  2020        4      NaN               13717         3.671160e+07

In [22]:
top_transactions_pincodes_df['pincodes'] = top_transactions_pincodes_df['pincodes'].fillna('Unknown')

In [23]:
top_transactions_pincodes_df[top_transactions_pincodes_df['pincodes'].isna()]

Empty DataFrame
Columns: [state, year, quarter, pincodes, transactions_count, transactions_amount]
Index: []

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [25]:
top_transactions_pincodes_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [27]:
top_transactions_pincodes_df['state'].value_counts()

state
andaman-&-nicobar-islands             280
andhra-pradesh                        280
arunachal-pradesh                     280
assam                                 280
bihar                                 280
chandigarh                            280
chhattisgarh                          280
delhi                                 280
goa                                   280
gujarat                               280
haryana                               280
himachal-pradesh                      280
jammu-&-kashmir                       280
jharkhand                             280
karnataka                             280
kerala                                280
ladakh                                280
madhya-pradesh                        280
maharashtra                           280
manipur                               280
meghalaya                             280
mizoram                               280
nagaland                              280
odisha                                280
puducherry                            280
punjab                                280
rajasthan                             280
sikkim                                280
tamil-nadu                            280
telangana                             280
tripura                               280
uttar-pradesh                         280
uttarakhand                           280
west-bengal                           280
dadra-&-nagar-haveli-&-daman-&-diu    254
lakshadweep                           225
Name: count, dtype: int64

In [28]:
top_transactions_pincodes_df['state'] = top_transactions_pincodes_df['state'].str.strip().str.title()

In [29]:
top_transactions_pincodes_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Districts Column Unique Values ##

In [30]:
top_transactions_pincodes_df['pincodes'].unique()

<ArrowStringArray>
['744101', '744103', '744102', '744105', '744104', '744107', '744301',
 '744112', '744202', '744302',
 ...
 '736121', '700001', '700014', '700015', '732125', '732201', '742202',
 '700161', '734001', '733134']
Length: 837, dtype: str

In [31]:
top_transactions_pincodes_df[top_transactions_pincodes_df['pincodes'] == '744103']

,state,year,quarter,pincodes,transactions_count,transactions_amount
1,Andaman-&-Nicobar-Islands,2018,1,744103,1223,2.238042e+06
11,Andaman-&-Nicobar-Islands,2018,2,744103,1965,4.752147e+06
21,Andaman-&-Nicobar-Islands,2018,3,744103,3182,1.018415e+07
31,Andaman-&-Nicobar-Islands,2018,4,744103,4576,1.702252e+07
40,Andaman-&-Nicobar-Islands,2019,1,744103,5742,1.940196e+07
51,Andaman-&-Nicobar-Islands,2019,2,744103,5847,2.375145e+07
60,Andaman-&-Nicobar-Islands,2019,3,744103,5680,1.990634e+07
72,Andaman-&-Nicobar-Islands,2019,4,744103,4840,1.979251e+07
81,Andaman-&-Nicobar-Islands,2020,1,744103,5870,2.200944e+07
91,Andaman-&-Nicobar-Islands,2020,2,744103,10035,2.619754e+07
101,Andaman-&-Nicobar-Islands,2020,3,744103,21272,6.033228e+07
110,Andaman-&-Nicobar-Islands,2020,4,744103,46884,1.382648e+08
121,Andaman-&-Nicobar-Islands,2021,1,744103,47328,1.584041e+08
131,Andaman-&-Nicobar-Islands,2021,2,744103,66321,1.747528e+08
141,Andaman-&-Nicobar-Islands,2021,3,744103,84790,2.464334e+08
151,Andaman-&-Nicobar-Islands,2021,4,744103,121613,3.722437e+08
161,Andaman-&-Nicobar-Islands,2022,1,744103,157230,3.997160e+08
171,Andaman-&-Nicobar-Islands,2022,2,744103,230746,5.611688e+08
181,Andaman-&-Nicobar-Islands,2022,3,744103,259994,5.456537e+08
191,Andaman-&-Nicobar-Islands,2022,4,744103,304600,6.129293e+08
200,Andaman-&-Nicobar-Islands,2023,1,744103,503053,9.695947e+08
210,Andaman-&-Nicobar-Islands,2023,2,744103,597774,1.119274e+09
220,Andaman-&-Nicobar-Islands,2023,3,744103,697625,1.158992e+09
230,Andaman-&-Nicobar-Islands,2023,4,744103,817988,1.376084e+09
240,Andaman-&-Nicobar-Islands,2024,1,744103,915265,1.466185e+09
250,Andaman-&-Nicobar-Islands,2024,2,744103,1017612,1.578926e+09
260,Andaman-&-Nicobar-Islands,2024,3,744103,1447958,2.053970e+09
270,Andaman-&-Nicobar-Islands,2024,4,744103,1624936,2.327920e+09

## VALIDATE FINAL DATASET INTEGRITY ##

In [32]:
top_transactions_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                9999 non-null   str
 1   year                 9999 non-null   str
 2   quarter              9999 non-null   int64
 3   pincodes             9999 non-null   str
 4   transactions_count   9999 non-null   int64
 5   transactions_amount  9999 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 667.4 KB

In [33]:
top_transactions_pincodes_df['year'] = top_transactions_pincodes_df['year'].astype('int32')
top_transactions_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                9999 non-null   str
 1   year                 9999 non-null   int32
 2   quarter              9999 non-null   int64
 3   pincodes             9999 non-null   str
 4   transactions_count   9999 non-null   int64
 5   transactions_amount  9999 non-null   float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 589.3 KB

In [34]:
top_transactions_pincodes_df

,state,year,quarter,pincodes,transactions_count,transactions_amount
0,Andaman-&-Nicobar-Islands,2018,1,744101,1622,2.769298e+06
1,Andaman-&-Nicobar-Islands,2018,1,744103,1223,2.238042e+06
2,Andaman-&-Nicobar-Islands,2018,1,744102,969,3.519060e+06
3,Andaman-&-Nicobar-Islands,2018,1,744105,685,1.298561e+06
4,Andaman-&-Nicobar-Islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,West-Bengal,2024,4,711101,6753348,1.049483e+10
9995,West-Bengal,2024,4,700059,6662715,8.009476e+09
9996,West-Bengal,2024,4,700039,6575693,9.018748e+09
9997,West-Bengal,2024,4,734001,6432082,8.996529e+09
9998,West-Bengal,2024,4,733134,6313560,1.050259e+10

In [35]:
top_transactions_pincodes_df

,state,year,quarter,pincodes,transactions_count,transactions_amount
0,Andaman-&-Nicobar-Islands,2018,1,744101,1622,2.769298e+06
1,Andaman-&-Nicobar-Islands,2018,1,744103,1223,2.238042e+06
2,Andaman-&-Nicobar-Islands,2018,1,744102,969,3.519060e+06
3,Andaman-&-Nicobar-Islands,2018,1,744105,685,1.298561e+06
4,Andaman-&-Nicobar-Islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,West-Bengal,2024,4,711101,6753348,1.049483e+10
9995,West-Bengal,2024,4,700059,6662715,8.009476e+09
9996,West-Bengal,2024,4,700039,6575693,9.018748e+09
9997,West-Bengal,2024,4,734001,6432082,8.996529e+09
9998,West-Bengal,2024,4,733134,6313560,1.050259e+10

In [36]:
top_transactions_pincodes_df['pincodes'] = top_transactions_pincodes_df['pincodes'].str.strip().str.title()

In [37]:
top_transactions_pincodes_df['pincodes']

0       744101
1       744103
2       744102
3       744105
4       744104
         ...
9994    711101
9995    700059
9996    700039
9997    734001
9998    733134
Name: pincodes, Length: 9999, dtype: str

In [38]:
top_transactions_pincodes_df

,state,year,quarter,pincodes,transactions_count,transactions_amount
0,Andaman-&-Nicobar-Islands,2018,1,744101,1622,2.769298e+06
1,Andaman-&-Nicobar-Islands,2018,1,744103,1223,2.238042e+06
2,Andaman-&-Nicobar-Islands,2018,1,744102,969,3.519060e+06
3,Andaman-&-Nicobar-Islands,2018,1,744105,685,1.298561e+06
4,Andaman-&-Nicobar-Islands,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,West-Bengal,2024,4,711101,6753348,1.049483e+10
9995,West-Bengal,2024,4,700059,6662715,8.009476e+09
9996,West-Bengal,2024,4,700039,6575693,9.018748e+09
9997,West-Bengal,2024,4,734001,6432082,8.996529e+09
9998,West-Bengal,2024,4,733134,6313560,1.050259e+10

In [39]:
top_transactions_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                9999 non-null   str
 1   year                 9999 non-null   int32
 2   quarter              9999 non-null   int64
 3   pincodes             9999 non-null   str
 4   transactions_count   9999 non-null   int64
 5   transactions_amount  9999 non-null   float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 590.5 KB

In [40]:
top_transactions_pincodes_df['pincodes'].unique()

<ArrowStringArray>
['744101', '744103', '744102', '744105', '744104', '744107', '744301',
 '744112', '744202', '744302',
 ...
 '736121', '700001', '700014', '700015', '732125', '732201', '742202',
 '700161', '734001', '733134']
Length: 837, dtype: str

In [41]:
top_transactions_pincodes_df['pincodes'] = top_transactions_pincodes_df['pincodes'].astype('category')

In [42]:
top_transactions_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                9999 non-null   str
 1   year                 9999 non-null   int32
 2   quarter              9999 non-null   int64
 3   pincodes             9999 non-null   category
 4   transactions_count   9999 non-null   int64
 5   transactions_amount  9999 non-null   float64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 483.7 KB

## Create transactions_pincodes_top Table In Database ##

In [43]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS transactions_pincodes_top (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,    
        pincodes VARCHAR(255) NOT NULL,
        transactions_count BIGINT,
        transactions_amount BIGINT
    );
""")

cur.execute("SELECT to_regclass('public.transactions_pincodes_top')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'transactions_pincodes_top' created successfully")

Table exists in PostgreSQL: transactions_pincodes_top
Table 'transactions_pincodes_top' created successfully

## Inserting Data from Data Frame to Transactions_Pincodes_Top Table ##

In [46]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in top_transactions_pincodes_df.iterrows():
    cur.execute(
        """
        INSERT INTO transactions_pincodes_top (
            state,
            year,
            quarter,
            pincodes,
            transactions_count,
            transactions_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["pincodes"],
            row["transactions_count"],
            row["transactions_amount"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully