# Transaction data analysis #

In [2]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\map\\transaction\\hover\\country\\india\\state\\"
map_state_list=os.listdir(path)
map_state_list

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

clm={'state':[], 'year':[],'quarter':[],'region_name':[], 'transaction_count':[], 'transaction_amount':[]}

for i in map_state_list:
    p_i=path+i+"\\"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"\\"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for m in D['data']['hoverDataList']:
                name = m['name']
                for n in m['metric']:
                    count = n['count']
                    amount = n['amount']
                    clm['region_name'].append(name)
                    clm['transaction_count'].append(count)
                    clm['transaction_amount'].append(amount)
                    clm['state'].append(i)
                    clm['year'].append(j)
                    clm['quarter'].append(int(k.strip('.json')))


map_trans_df=pd.DataFrame(clm)

In [4]:
map_trans_df

,state,year,quarter,region_name,transaction_count,transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,west-bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,west-bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,west-bengal,2024,4,nadia district,65274337,1.079320e+11
20602,west-bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,west-bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [5]:
map_trans_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               20604 non-null  str
 1   year                20604 non-null  str
 2   quarter             20604 non-null  int64
 3   region_name         20604 non-null  str
 4   transaction_count   20604 non-null  int64
 5   transaction_amount  20604 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.6 MB

In [6]:
map_trans_df.shape

(20604, 6)

In [12]:
map_trans_df[(map_trans_df['quarter'] == 1) & (map_trans_df['state'] == 'andaman-&-nicobar-islands')]

,state,year,quarter,region_name,transaction_count,transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
12,andaman-&-nicobar-islands,2019,1,north and middle andaman district,3264,9.561709e+06
13,andaman-&-nicobar-islands,2019,1,south andaman district,25683,8.550197e+07
14,andaman-&-nicobar-islands,2019,1,nicobars district,1539,7.236060e+06
24,andaman-&-nicobar-islands,2020,1,north and middle andaman district,5674,1.469737e+07
25,andaman-&-nicobar-islands,2020,1,south andaman district,32713,1.346794e+08
26,andaman-&-nicobar-islands,2020,1,nicobars district,2911,1.209954e+07
36,andaman-&-nicobar-islands,2021,1,north and middle andaman district,27358,7.502726e+07
37,andaman-&-nicobar-islands,2021,1,south andaman district,207092,6.696040e+08
38,andaman-&-nicobar-islands,2021,1,nicobars district,10302,3.907527e+07
48,andaman-&-nicobar-islands,2022,1,north and middle andaman district,60059,1.616249e+08
49,andaman-&-nicobar-islands,2022,1,south andaman district,705512,1.872991e+09
50,andaman-&-nicobar-islands,2022,1,nicobars district,29177,9.441413e+07
60,andaman-&-nicobar-islands,2023,1,north and middle andaman district,152187,3.920803e+08
61,andaman-&-nicobar-islands,2023,1,south andaman district,2030078,3.867385e+09
62,andaman-&-nicobar-islands,2023,1,nicobars district,94127,2.020628e+08
72,andaman-&-nicobar-islands,2024,1,north and middle andaman district,266400,6.017561e+08
73,andaman-&-nicobar-islands,2024,1,south andaman district,3751724,5.952049e+09
74,andaman-&-nicobar-islands,2024,1,nicobars district,166796,3.053463e+08

In [14]:
map_trans_df[(map_trans_df['quarter'] == 1) & (map_trans_df['state'] == 'andaman-&-nicobar-islands')].shape

(21, 6)

In [16]:
map_trans_df.describe()

            quarter  transaction_count  transaction_amount
count  20604.000000       2.060400e+04        2.060400e+04
mean       2.505581       1.141935e+07        1.676967e+10
std        1.118047       4.534570e+07        5.655640e+10
min        1.000000       2.000000e+00        1.698886e+02
25%        2.000000       2.521455e+05        4.578292e+08
50%        3.000000       1.558070e+06        2.868918e+09
75%        4.000000       8.122777e+06        1.352423e+10
max        4.000000       1.674348e+09        1.790144e+12

In [17]:
map_trans_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [19]:
map_trans_df.isna().sum()

state                 0
year                  0
quarter               0
region_name           0
transaction_count     0
transaction_amount    0
dtype: int64

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [20]:
map_trans_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [21]:
map_trans_df['state'].value_counts()

state
uttar-pradesh                         2100
madhya-pradesh                        1462
bihar                                 1064
tamil-nadu                            1038
maharashtra                           1008
rajasthan                              958
assam                                  928
gujarat                                924
telangana                              924
karnataka                              842
odisha                                 840
chhattisgarh                           768
arunachal-pradesh                      698
jharkhand                              672
west-bengal                            644
punjab                                 618
haryana                                616
jammu-&-kashmir                        616
manipur                                448
kerala                                 392
andhra-pradesh                         390
uttarakhand                            364
himachal-pradesh                       336
nagaland                               318
meghalaya                              310
delhi                                  308
mizoram                                230
tripura                                224
sikkim                                 116
puducherry                             112
andaman-&-nicobar-islands               84
dadra-&-nagar-haveli-&-daman-&-diu      84
goa                                     56
ladakh                                  56
chandigarh                              28
lakshadweep                             28
Name: count, dtype: int64

In [22]:
map_trans_df['state'] = map_trans_df['state'].str.strip().str.title()

In [23]:
map_trans_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Region name Column Unique Values ##

In [24]:
map_trans_df['region_name'].unique()

<ArrowStringArray>
['north and middle andaman district',            'south andaman district',
                 'nicobars district',                  'nicobar district',
            'east godavari district',               'srikakulam district',
             'spsr nellore district',             'vizianagaram district',
            'visakhapatnam district',                 'prakasam district',
 ...
               'alipurduar district',        'paschim bardhaman district',
                    'nadia district',                  'birbhum district',
          'purba medinipur district',                   'maldah district',
                'darjiling district',               'darjeeling district',
              'cooch behar district',                    'malda district']
Length: 843, dtype: str

In [25]:
map_trans_df['region_name'] = map_trans_df['region_name'].str.strip().str.title()

In [26]:
map_trans_df['region_name'].unique()

<ArrowStringArray>
['North And Middle Andaman District',            'South Andaman District',
                 'Nicobars District',                  'Nicobar District',
            'East Godavari District',               'Srikakulam District',
             'Spsr Nellore District',             'Vizianagaram District',
            'Visakhapatnam District',                 'Prakasam District',
 ...
               'Alipurduar District',        'Paschim Bardhaman District',
                    'Nadia District',                  'Birbhum District',
          'Purba Medinipur District',                   'Maldah District',
                'Darjiling District',               'Darjeeling District',
              'Cooch Behar District',                    'Malda District']
Length: 843, dtype: str

In [28]:
map_trans_df

,state,year,quarter,region_name,transaction_count,transaction_amount
0,Andaman-&-Nicobar-Islands,2018,1,North And Middle Andaman District,442,9.316631e+05
1,Andaman-&-Nicobar-Islands,2018,1,South Andaman District,5688,1.256025e+07
2,Andaman-&-Nicobar-Islands,2018,1,Nicobars District,528,1.139849e+06
3,Andaman-&-Nicobar-Islands,2018,2,North And Middle Andaman District,825,1.317863e+06
4,Andaman-&-Nicobar-Islands,2018,2,South Andaman District,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West-Bengal,2024,4,Alipurduar District,15875637,2.099251e+10
20600,West-Bengal,2024,4,Paschim Bardhaman District,56616799,6.968735e+10
20601,West-Bengal,2024,4,Nadia District,65274337,1.079320e+11
20602,West-Bengal,2024,4,Birbhum District,36905213,5.778701e+10
20603,West-Bengal,2024,4,Purba Medinipur District,67833775,1.142771e+11

## VALIDATE FINAL DATASET INTEGRITY ##

In [42]:
map_trans_df.shape

(20604, 6)

In [31]:
map_trans_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               20604 non-null  str
 1   year                20604 non-null  str
 2   quarter             20604 non-null  int64
 3   region_name         20604 non-null  str
 4   transaction_count   20604 non-null  int64
 5   transaction_amount  20604 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.6 MB

In [33]:
map_trans_df['quarter'].unique()

array([1, 2, 3, 4])

In [34]:
map_trans_df['region_name'] = map_trans_df['region_name'].astype('category')

In [35]:
map_trans_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               20604 non-null  str
 1   year                20604 non-null  str
 2   quarter             20604 non-null  int64
 3   region_name         20604 non-null  category
 4   transaction_count   20604 non-null  int64
 5   transaction_amount  20604 non-null  float64
dtypes: category(1), float64(1), int64(2), str(2)
memory usage: 1.1 MB

In [37]:
map_trans_df['year'] = map_trans_df['year'].astype('int32')

In [38]:
map_trans_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               20604 non-null  str
 1   year                20604 non-null  int32
 2   quarter             20604 non-null  int64
 3   region_name         20604 non-null  category
 4   transaction_count   20604 non-null  int64
 5   transaction_amount  20604 non-null  float64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 988.8 KB

## Create Connection and database ##

In [ ]:
import psycopg2

DB_NAME = "smart_pay"
conn_params = {
    "host": "localhost",
    "database": "postgres",
    "user": "postgres",
    "password": "",
}

conn = psycopg2.connect(**conn_params)
conn.autocommit = True
cur = conn.cursor()

cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,))
exists = cur.fetchone()

if not exists:
    cur.execute(f'CREATE DATABASE "{DB_NAME}"')
    print(f"Database '{DB_NAME}' created successfully")
else:
    print(f"Database '{DB_NAME}' already exists")

cur.close()
conn.close()

Database 'smart_pay' already exists

## Create Map_Transaction Table In Database ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS map_transaction (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER,
        region_name VARCHAR(255),
        transaction_count BIGINT,
        transaction_amount NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.map_transaction')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'map_transaction' created successfully")

Table exists in PostgreSQL: map_transaction
Table 'map_transaction' created successfully

## Inserting Data from Data Frame to Transaction_data Table ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in map_trans_df.iterrows():
    cur.execute(
        """
        INSERT INTO map_transaction (
            state,
            year,
            quarter,
            region_name,
            transaction_count,
            transaction_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["region_name"],
            row["transaction_count"],
            row["transaction_amount"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()
cur.execute("""ALTER TABLE map_transaction
RENAME TO transaction_map;""")


conn.commit()
cur.close()
conn.close()
print("Table name changed to transaction_map successfully")

Table name changed to transaction_map successfully