# User data analysis #

In [1]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\map\\user\\hover\\country\\india\\state\\"
map_state_list=os.listdir(path)
map_state_list

clm={'state':[], 'year':[],'quarter':[],'region_name':[], 'registeredUsers':[], 'appOpens':[]}

for i in map_state_list:
    p_i=path+i+"\\"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"\\"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            hover_data = D['data']['hoverData']
            for region_name, values in hover_data.items():
                clm['region_name'].append(region_name)
                clm['registeredUsers'].append(values['registeredUsers'])
                clm['appOpens'].append(values['appOpens'])
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))


map_user_df=pd.DataFrame(clm)

In [2]:
map_user_df

,state,year,quarter,region_name,registeredUsers,appOpens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,west-bengal,2024,4,alipurduar district,475688,31842355
20604,west-bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,west-bengal,2024,4,nadia district,1861738,98740305
20606,west-bengal,2024,4,birbhum district,1114220,73465525
20607,west-bengal,2024,4,purba medinipur district,1717074,108350777

In [3]:
map_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            20608 non-null  str
 1   year             20608 non-null  str
 2   quarter          20608 non-null  int64
 3   region_name      20608 non-null  str
 4   registeredUsers  20608 non-null  int64
 5   appOpens         20608 non-null  int64
dtypes: int64(3), str(3)
memory usage: 1.6 MB

In [5]:
map_user_df.shape

(20608, 6)

In [6]:
map_user_df[(map_user_df['quarter'] == 1) & (map_user_df['state'] == 'andaman-&-nicobar-islands')]

,state,year,quarter,region_name,registeredUsers,appOpens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
12,andaman-&-nicobar-islands,2019,1,north and middle andaman district,2013,0
13,andaman-&-nicobar-islands,2019,1,south andaman district,15961,0
14,andaman-&-nicobar-islands,2019,1,nicobars district,622,0
24,andaman-&-nicobar-islands,2020,1,north and middle andaman district,3315,30444
25,andaman-&-nicobar-islands,2020,1,south andaman district,24174,151529
26,andaman-&-nicobar-islands,2020,1,nicobars district,879,11613
36,andaman-&-nicobar-islands,2021,1,north and middle andaman district,7833,121680
37,andaman-&-nicobar-islands,2021,1,south andaman district,48352,837589
38,andaman-&-nicobar-islands,2021,1,nicobars district,1573,45067
48,andaman-&-nicobar-islands,2022,1,north and middle andaman district,10720,904869
49,andaman-&-nicobar-islands,2022,1,south andaman district,63487,2368756
50,andaman-&-nicobar-islands,2022,1,nicobars district,2081,573782
60,andaman-&-nicobar-islands,2023,1,north and middle andaman district,12941,3103047
61,andaman-&-nicobar-islands,2023,1,south andaman district,77052,5450795
62,andaman-&-nicobar-islands,2023,1,nicobars district,2491,2458822
72,andaman-&-nicobar-islands,2024,1,north and middle andaman district,15539,9022450
73,andaman-&-nicobar-islands,2024,1,south andaman district,89907,12147903
74,andaman-&-nicobar-islands,2024,1,nicobars district,2965,7368398

In [7]:
map_user_df[(map_user_df['quarter'] == 1) & (map_user_df['state'] == 'andaman-&-nicobar-islands')].shape

(21, 6)

In [8]:
map_user_df.describe()

            quarter  registeredUsers      appOpens
count  20608.000000     2.060800e+04  2.060800e+04
mean       2.505435     4.301338e+05  1.952097e+07
std        1.118048     8.148492e+05  4.004047e+07
min        1.000000     2.200000e+01  0.000000e+00
25%        2.000000     6.208525e+04  4.839385e+05
50%        3.000000     1.995320e+05  5.946804e+06
75%        4.000000     4.896048e+05  2.191529e+07
max        4.000000     1.812748e+07  1.137875e+09

In [9]:
map_user_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [10]:
map_user_df.isna().sum()

state              0
year               0
quarter            0
region_name        0
registeredUsers    0
appOpens           0
dtype: int64

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [11]:
map_user_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [12]:
map_user_df['state'].value_counts()

state
uttar-pradesh                         2100
madhya-pradesh                        1462
bihar                                 1064
tamil-nadu                            1038
maharashtra                           1008
rajasthan                              958
assam                                  928
gujarat                                924
telangana                              924
karnataka                              842
odisha                                 840
chhattisgarh                           768
arunachal-pradesh                      702
jharkhand                              672
west-bengal                            644
punjab                                 618
haryana                                616
jammu-&-kashmir                        616
manipur                                448
kerala                                 392
andhra-pradesh                         390
uttarakhand                            364
himachal-pradesh                       336
nagaland                               318
meghalaya                              310
delhi                                  308
mizoram                                230
tripura                                224
sikkim                                 116
puducherry                             112
andaman-&-nicobar-islands               84
dadra-&-nagar-haveli-&-daman-&-diu      84
goa                                     56
ladakh                                  56
chandigarh                              28
lakshadweep                             28
Name: count, dtype: int64

In [13]:
map_user_df['state'] = map_user_df['state'].str.strip().str.title()

In [14]:
map_user_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Region name Column Unique Values ##

In [15]:
map_user_df['region_name'].unique()

<ArrowStringArray>
['north and middle andaman district',            'south andaman district',
                 'nicobars district',                  'nicobar district',
            'east godavari district',               'srikakulam district',
            'visakhapatnam district',                 'prakasam district',
                'anantapur district',                  'kurnool district',
 ...
               'alipurduar district',        'paschim bardhaman district',
                    'nadia district',                  'birbhum district',
          'purba medinipur district',                   'maldah district',
                'darjiling district',               'darjeeling district',
              'cooch behar district',                    'malda district']
Length: 843, dtype: str

In [16]:
map_user_df['region_name'] = map_user_df['region_name'].str.strip().str.title()

In [17]:
map_user_df['region_name'].unique()

<ArrowStringArray>
['North And Middle Andaman District',            'South Andaman District',
                 'Nicobars District',                  'Nicobar District',
            'East Godavari District',               'Srikakulam District',
            'Visakhapatnam District',                 'Prakasam District',
                'Anantapur District',                  'Kurnool District',
 ...
               'Alipurduar District',        'Paschim Bardhaman District',
                    'Nadia District',                  'Birbhum District',
          'Purba Medinipur District',                   'Maldah District',
                'Darjiling District',               'Darjeeling District',
              'Cooch Behar District',                    'Malda District']
Length: 843, dtype: str

In [18]:
map_user_df

,state,year,quarter,region_name,registeredUsers,appOpens
0,Andaman-&-Nicobar-Islands,2018,1,North And Middle Andaman District,632,0
1,Andaman-&-Nicobar-Islands,2018,1,South Andaman District,5846,0
2,Andaman-&-Nicobar-Islands,2018,1,Nicobars District,262,0
3,Andaman-&-Nicobar-Islands,2018,2,North And Middle Andaman District,911,0
4,Andaman-&-Nicobar-Islands,2018,2,South Andaman District,8143,0
...,...,...,...,...,...,...
20603,West-Bengal,2024,4,Alipurduar District,475688,31842355
20604,West-Bengal,2024,4,Paschim Bardhaman District,1468252,80543469
20605,West-Bengal,2024,4,Nadia District,1861738,98740305
20606,West-Bengal,2024,4,Birbhum District,1114220,73465525
20607,West-Bengal,2024,4,Purba Medinipur District,1717074,108350777

## VALIDATE FINAL DATASET INTEGRITY ##

In [19]:
map_user_df.shape

(20608, 6)

In [20]:
map_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            20608 non-null  str
 1   year             20608 non-null  str
 2   quarter          20608 non-null  int64
 3   region_name      20608 non-null  str
 4   registeredUsers  20608 non-null  int64
 5   appOpens         20608 non-null  int64
dtypes: int64(3), str(3)
memory usage: 1.6 MB

In [21]:
map_user_df['quarter'].unique()

array([1, 2, 3, 4])

In [22]:
map_user_df['region_name'] = map_user_df['region_name'].astype('category')

In [23]:
map_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            20608 non-null  str
 1   year             20608 non-null  str
 2   quarter          20608 non-null  int64
 3   region_name      20608 non-null  category
 4   registeredUsers  20608 non-null  int64
 5   appOpens         20608 non-null  int64
dtypes: category(1), int64(3), str(2)
memory usage: 1.1 MB

In [24]:
map_user_df['year'] = map_user_df['year'].astype('int32')

In [25]:
map_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            20608 non-null  str
 1   year             20608 non-null  int32
 2   quarter          20608 non-null  int64
 3   region_name      20608 non-null  category
 4   registeredUsers  20608 non-null  int64
 5   appOpens         20608 non-null  int64
dtypes: category(1), int32(1), int64(3), str(1)
memory usage: 989.1 KB

## Create Map_User Table In Database ##

In [26]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS user_map (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER,
        region_name VARCHAR(255),
        registeredUsers BIGINT,
        appOpens NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.user_map')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'user_map' created successfully")

Table exists in PostgreSQL: user_map
Table 'user_map' created successfully

## Inserting Data from Data Frame to user_map Table ##

In [27]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in map_user_df.iterrows():
    cur.execute(
        """
        INSERT INTO user_map (
            state,
            year,
            quarter,
            region_name,
            registeredUsers,
            appOpens
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["region_name"],
            row["registeredUsers"],
            row["appOpens"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully

In [28]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()
cur.execute("""ALTER TABLE map_insurance
RENAME TO insurance_map;""")


conn.commit()
cur.close()
conn.close()
print("Table name changed to transaction_map successfully")

Table name changed to transaction_map successfully