# Transaction data analysis #

In [1]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\aggregated\\transaction\\country\\india\\state\\"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"\\"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"\\"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transacion_type'].append(Name)
              clm['Transacion_count'].append(count)
              clm['Transacion_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Agg_Trans=pd.DataFrame(clm)

In [3]:
Agg_Trans

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [4]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              5034 non-null   str
 1   Year               5034 non-null   str
 2   Quater             5034 non-null   int64
 3   Transacion_type    5034 non-null   str
 4   Transacion_count   5034 non-null   int64
 5   Transacion_amount  5034 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 390.8 KB

In [5]:
Agg_Trans.shape

(5034, 6)

In [6]:
Agg_Trans[Agg_Trans['State'] == 'andaman-&-nicobar-islands']

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
135,andaman-&-nicobar-islands,2024,4,Merchant payments,3666060,2.546601e+09
136,andaman-&-nicobar-islands,2024,4,Peer-to-peer payments,1993301,6.142805e+09
137,andaman-&-nicobar-islands,2024,4,Recharge & bill payments,389318,2.149123e+08
138,andaman-&-nicobar-islands,2024,4,Financial Services,12889,1.278996e+07
139,andaman-&-nicobar-islands,2024,4,Others,2332,3.835931e+06

In [7]:
Agg_Trans.describe()

            Quater  Transacion_count  Transacion_amount
count  5034.000000      5.034000e+03       5.034000e+03
mean      2.500795      4.673902e+07       6.863772e+10
std       1.118145      1.690968e+08       2.685200e+11
min       1.000000      2.000000e+00       3.439721e+01
25%       2.000000      5.808950e+04       3.993888e+07
50%       3.000000      5.158310e+05       4.394139e+08
75%       4.000000      1.166629e+07       1.102822e+10
max       4.000000      2.393918e+09       3.095666e+12

In [8]:
Agg_Trans.duplicated().sum()

np.int64(0)

## Checking Duplicates Across All Columns ##

In [9]:
Agg_Trans[Agg_Trans.duplicated(subset=['State'])]

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
5,andaman-&-nicobar-islands,2018,2,Recharge & bill payments,6735,2.320945e+06
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [10]:
Agg_Trans[Agg_Trans.duplicated(subset=['Year'])]

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
5,andaman-&-nicobar-islands,2018,2,Recharge & bill payments,6735,2.320945e+06
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [11]:
Agg_Trans[Agg_Trans.duplicated(subset=['Quater'])]

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
6,andaman-&-nicobar-islands,2018,2,Peer-to-peer payments,3575,2.451193e+07
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [12]:
Agg_Trans[Agg_Trans.duplicated(subset=['Transacion_type'])]

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
5,andaman-&-nicobar-islands,2018,2,Recharge & bill payments,6735,2.320945e+06
6,andaman-&-nicobar-islands,2018,2,Peer-to-peer payments,3575,2.451193e+07
7,andaman-&-nicobar-islands,2018,2,Merchant payments,603,1.024491e+06
8,andaman-&-nicobar-islands,2018,2,Financial Services,59,1.213360e+05
9,andaman-&-nicobar-islands,2018,2,Others,368,3.598385e+05
...,...,...,...,...,...,...
5029,west-bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,west-bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,west-bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,west-bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,west-bengal,2024,4,Others,421806,5.053641e+08

In [13]:
Agg_Trans[Agg_Trans.duplicated(subset=['Transacion_count'])]

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
303,arunachal-pradesh,2019,1,Financial Services,256,1.406229e+05
732,chandigarh,2019,3,Recharge & bill payments,308219,2.138849e+08
753,chandigarh,2020,3,Financial Services,2643,5.254415e+06
998,dadra-&-nagar-haveli-&-daman-&-diu,2018,4,Financial Services,2996,3.716747e+05
1048,dadra-&-nagar-haveli-&-daman-&-diu,2021,2,Financial Services,1826,1.763793e+06
...,...,...,...,...,...,...
4481,tripura,2018,2,Merchant payments,9621,1.057095e+07
4508,tripura,2019,3,Others,5646,5.524359e+06
4512,tripura,2019,4,Financial Services,2239,3.770977e+05
4528,tripura,2020,3,Others,6819,3.886908e+06
4578,tripura,2023,1,Others,11481,7.160536e+06

In [14]:
Agg_Trans[Agg_Trans.duplicated(subset=['Transacion_amount'])]

Empty DataFrame
Columns: [State, Year, Quater, Transacion_type, Transacion_count, Transacion_amount]
Index: []

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [15]:
Agg_Trans.isna().sum()

State                0
Year                 0
Quater               0
Transacion_type      0
Transacion_count     0
Transacion_amount    0
dtype: int64

In [16]:
Agg_Trans['State'].isna().sum()

np.int64(0)

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [17]:
Agg_Trans['State'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [18]:
Agg_Trans['State'].value_counts()

State
andaman-&-nicobar-islands             140
andhra-pradesh                        140
arunachal-pradesh                     140
assam                                 140
bihar                                 140
chandigarh                            140
chhattisgarh                          140
dadra-&-nagar-haveli-&-daman-&-diu    140
delhi                                 140
goa                                   140
gujarat                               140
haryana                               140
himachal-pradesh                      140
jammu-&-kashmir                       140
jharkhand                             140
karnataka                             140
kerala                                140
ladakh                                140
madhya-pradesh                        140
maharashtra                           140
manipur                               140
meghalaya                             140
mizoram                               140
nagaland                              140
odisha                                140
puducherry                            140
punjab                                140
rajasthan                             140
sikkim                                140
tamil-nadu                            140
telangana                             140
tripura                               140
uttar-pradesh                         140
uttarakhand                           140
west-bengal                           140
lakshadweep                           134
Name: count, dtype: int64

In [19]:
Agg_Trans['State'] = Agg_Trans['State'].str.strip().str.title()

In [20]:
Agg_Trans['State'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Transacion type Column Unique Values ##

In [21]:
Agg_Trans['Transacion_type'].unique()

<ArrowStringArray>
['Recharge & bill payments',    'Peer-to-peer payments',
        'Merchant payments',       'Financial Services',
                   'Others']
Length: 5, dtype: str

In [22]:
Agg_Trans['Transacion_type'] = Agg_Trans['Transacion_type'].str.strip().str.title()

In [23]:
Agg_Trans['Transacion_type'].unique()

<ArrowStringArray>
['Recharge & Bill Payments',    'Peer-To-Peer Payments',
        'Merchant Payments',       'Financial Services',
                   'Others']
Length: 5, dtype: str

In [24]:
Agg_Trans

,State,Year,Quater,Transacion_type,Transacion_count,Transacion_amount
0,Andaman-&-Nicobar-Islands,2018,1,Recharge & Bill Payments,4200,1.845307e+06
1,Andaman-&-Nicobar-Islands,2018,1,Peer-To-Peer Payments,1871,1.213866e+07
2,Andaman-&-Nicobar-Islands,2018,1,Merchant Payments,298,4.525072e+05
3,Andaman-&-Nicobar-Islands,2018,1,Financial Services,33,1.060142e+04
4,Andaman-&-Nicobar-Islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West-Bengal,2024,4,Merchant Payments,655100809,3.892862e+11
5030,West-Bengal,2024,4,Peer-To-Peer Payments,493217788,1.361927e+12
5031,West-Bengal,2024,4,Recharge & Bill Payments,76043195,5.753406e+10
5032,West-Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West-Bengal,2024,4,Others,421806,5.053641e+08

## Correcting Column Header Names ##

In [25]:
Agg_Trans.columns = ['State','Year','Quarter','Transaction_type','Transaction_count','Transaction_amount']

In [26]:
Agg_Trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman-&-Nicobar-Islands,2018,1,Recharge & Bill Payments,4200,1.845307e+06
1,Andaman-&-Nicobar-Islands,2018,1,Peer-To-Peer Payments,1871,1.213866e+07
2,Andaman-&-Nicobar-Islands,2018,1,Merchant Payments,298,4.525072e+05
3,Andaman-&-Nicobar-Islands,2018,1,Financial Services,33,1.060142e+04
4,Andaman-&-Nicobar-Islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West-Bengal,2024,4,Merchant Payments,655100809,3.892862e+11
5030,West-Bengal,2024,4,Peer-To-Peer Payments,493217788,1.361927e+12
5031,West-Bengal,2024,4,Recharge & Bill Payments,76043195,5.753406e+10
5032,West-Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West-Bengal,2024,4,Others,421806,5.053641e+08

## VALIDATE FINAL DATASET INTEGRITY ##

In [27]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   str
 1   Year                5034 non-null   str
 2   Quarter             5034 non-null   int64
 3   Transaction_type    5034 non-null   str
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 392.1 KB

In [28]:
Agg_Trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman-&-Nicobar-Islands,2018,1,Recharge & Bill Payments,4200,1.845307e+06
1,Andaman-&-Nicobar-Islands,2018,1,Peer-To-Peer Payments,1871,1.213866e+07
2,Andaman-&-Nicobar-Islands,2018,1,Merchant Payments,298,4.525072e+05
3,Andaman-&-Nicobar-Islands,2018,1,Financial Services,33,1.060142e+04
4,Andaman-&-Nicobar-Islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West-Bengal,2024,4,Merchant Payments,655100809,3.892862e+11
5030,West-Bengal,2024,4,Peer-To-Peer Payments,493217788,1.361927e+12
5031,West-Bengal,2024,4,Recharge & Bill Payments,76043195,5.753406e+10
5032,West-Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West-Bengal,2024,4,Others,421806,5.053641e+08

In [29]:
Agg_Trans['Year'] = pd.to_datetime(Agg_Trans['Year'], format='%Y')

In [30]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   str
 1   Year                5034 non-null   datetime64[us]
 2   Quarter             5034 non-null   int64
 3   Transaction_type    5034 non-null   str
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 372.4 KB

## CHECKING OUTLIERS ###

In [31]:
Agg_Trans.loc[Agg_Trans["Transaction_amount"] < 0, "Transaction_amount"]

Series([], Name: Transaction_amount, dtype: float64)

In [32]:
Agg_Trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman-&-Nicobar-Islands,2018-01-01,1,Recharge & Bill Payments,4200,1.845307e+06
1,Andaman-&-Nicobar-Islands,2018-01-01,1,Peer-To-Peer Payments,1871,1.213866e+07
2,Andaman-&-Nicobar-Islands,2018-01-01,1,Merchant Payments,298,4.525072e+05
3,Andaman-&-Nicobar-Islands,2018-01-01,1,Financial Services,33,1.060142e+04
4,Andaman-&-Nicobar-Islands,2018-01-01,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West-Bengal,2024-01-01,4,Merchant Payments,655100809,3.892862e+11
5030,West-Bengal,2024-01-01,4,Peer-To-Peer Payments,493217788,1.361927e+12
5031,West-Bengal,2024-01-01,4,Recharge & Bill Payments,76043195,5.753406e+10
5032,West-Bengal,2024-01-01,4,Financial Services,2352084,8.472965e+08
5033,West-Bengal,2024-01-01,4,Others,421806,5.053641e+08

In [33]:
Agg_Trans.loc[Agg_Trans["Transaction_count"] < 0, "Transaction_count"]

Series([], Name: Transaction_count, dtype: int64)

In [34]:
Agg_Trans['Quarter'].unique()

array([1, 2, 3, 4])

In [35]:
Agg_Trans['Transaction_type'] = Agg_Trans['Transaction_type'].astype('category')

In [36]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   str
 1   Year                5034 non-null   datetime64[us]
 2   Quarter             5034 non-null   int64
 3   Transaction_type    5034 non-null   category
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: category(1), datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 252.9 KB

In [37]:
Agg_Trans

,State,Year,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman-&-Nicobar-Islands,2018-01-01,1,Recharge & Bill Payments,4200,1.845307e+06
1,Andaman-&-Nicobar-Islands,2018-01-01,1,Peer-To-Peer Payments,1871,1.213866e+07
2,Andaman-&-Nicobar-Islands,2018-01-01,1,Merchant Payments,298,4.525072e+05
3,Andaman-&-Nicobar-Islands,2018-01-01,1,Financial Services,33,1.060142e+04
4,Andaman-&-Nicobar-Islands,2018-01-01,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West-Bengal,2024-01-01,4,Merchant Payments,655100809,3.892862e+11
5030,West-Bengal,2024-01-01,4,Peer-To-Peer Payments,493217788,1.361927e+12
5031,West-Bengal,2024-01-01,4,Recharge & Bill Payments,76043195,5.753406e+10
5032,West-Bengal,2024-01-01,4,Financial Services,2352084,8.472965e+08
5033,West-Bengal,2024-01-01,4,Others,421806,5.053641e+08

In [56]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   str
 1   Year                5034 non-null   datetime64[us]
 2   Quarter             5034 non-null   int64
 3   Transaction_type    5034 non-null   category
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: category(1), datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 252.9 KB

In [57]:
Agg_Trans["Year"] = Agg_Trans["Year"].dt.year

In [58]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   str
 1   Year                5034 non-null   int32
 2   Quarter             5034 non-null   int64
 3   Transaction_type    5034 non-null   category
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 233.3 KB

In [59]:
Agg_Trans.rename(columns={
    "State": "state",
    "Year": "year",
    "Quarter": "quarter",
    "Transaction_type": "transaction_type",
    "Transaction_count": "transaction_count",
    "Transaction_amount": "transaction_amount"
}, inplace=True)

In [61]:
Agg_Trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               5034 non-null   str
 1   year                5034 non-null   int32
 2   quarter             5034 non-null   int64
 3   transaction_type    5034 non-null   category
 4   transaction_count   5034 non-null   int64
 5   transaction_amount  5034 non-null   float64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 233.3 KB

## Create Connection and database ##

In [54]:
import psycopg2

DB_NAME = "smart_pay"
conn_params = {
    "host": "localhost",
    "database": "postgres",
    "user": "postgres",
    "password": "HareKrishna@143",
}

conn = psycopg2.connect(**conn_params)
conn.autocommit = True
cur = conn.cursor()

cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,))
exists = cur.fetchone()

if not exists:
    cur.execute(f'CREATE DATABASE "{DB_NAME}"')
    print(f"Database '{DB_NAME}' created successfully")
else:
    print(f"Database '{DB_NAME}' already exists")

cur.close()
conn.close()

Database 'smart_pay' already exists

## Create Transaction Table In Database ##

In [55]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS transaction_data (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER,
        transaction_type VARCHAR(255),
        transaction_count BIGINT,
        transaction_amount NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.transaction_data')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'transaction_data' created successfully")

Table exists in PostgreSQL: transaction_data
Table 'transaction_data' created successfully

## Inserting Data from Data Frame to Transaction_data Table ##

In [62]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in Agg_Trans.iterrows():
    cur.execute(
        """
        INSERT INTO transaction_data (
            state,
            year,
            quarter,
            transaction_type,
            transaction_count,
            transaction_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["transaction_type"],
            row["transaction_count"],
            row["transaction_amount"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully

In [2]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()
cur.execute("""ALTER TABLE transaction_data
RENAME TO transaction_agg;""")


conn.commit()
cur.close()
conn.close()
print("Table name changed to transaction_agg successfully")

Table name changed to transaction_agg successfully