# User Data Analysis
Notebook for exploring user-related datasets.

In [122]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\aggregated\\user\\country\\india\\state\\"
Agg_user_list=os.listdir(path)
Agg_user_list

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm = { 'State': [], 'Year': [], 'Quarter': [],'Registered_Users': [], 'App_Opens': [],'brand': [], 'count': [], 'percentage': []}

for i in Agg_user_list:
    p_i = path + i + "\\"
    Agg_yr = os.listdir(p_i)
    for j in Agg_yr:
        p_j = p_i + j + "\\"
        Agg_yr_list = os.listdir(p_j)
        for k in Agg_yr_list:
            p_k = p_j + k
            with open(p_k, 'r', encoding="utf-8") as Data:
                D = json.load(Data)

            Registered_Users = D['data']['aggregated']['registeredUsers']
            App_Opens = D['data']['aggregated']['appOpens']

            if D['data']['usersByDevice'] is not None:
                for y in D['data']['usersByDevice']:
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
                    clm['Registered_Users'].append(Registered_Users)
                    clm['App_Opens'].append(App_Opens)
                    clm['brand'].append(y['brand'])
                    clm['count'].append(y['count'])
                    clm['percentage'].append(y['percentage'])
            else:
                clm['State'].append(i)
                clm['Year'].append(j)
                clm['Quarter'].append(int(k.strip('.json')))
                clm['Registered_Users'].append(Registered_Users)
                clm['App_Opens'].append(App_Opens)
                clm['brand'].append(None)
                clm['count'].append(None)
                clm['percentage'].append(None)

Agg_user_df = pd.DataFrame(clm)

In [123]:
Agg_user_df

,State,Year,Quarter,Registered_Users,App_Opens,brand,count,percentage
0,andaman-&-nicobar-islands,2018,1,6740,0,Xiaomi,1665.0,0.247033
1,andaman-&-nicobar-islands,2018,1,6740,0,Samsung,1445.0,0.214392
2,andaman-&-nicobar-islands,2018,1,6740,0,Vivo,982.0,0.145697
3,andaman-&-nicobar-islands,2018,1,6740,0,Oppo,501.0,0.074332
4,andaman-&-nicobar-islands,2018,1,6740,0,OnePlus,332.0,0.049258
...,...,...,...,...,...,...,...,...
7123,west-bengal,2023,4,30064546,1467442959,NaN,NaN,NaN
7124,west-bengal,2024,1,31306843,633526507,NaN,NaN,NaN
7125,west-bengal,2024,2,32540397,704276274,NaN,NaN,NaN
7126,west-bengal,2024,3,33612828,709864323,NaN,NaN,NaN
7127,west-bengal,2024,4,34750181,1994940763,NaN,NaN,NaN

In [124]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             7128 non-null   str
 1   Year              7128 non-null   str
 2   Quarter           7128 non-null   int64
 3   Registered_Users  7128 non-null   int64
 4   App_Opens         7128 non-null   int64
 5   brand             6732 non-null   str
 6   count             6732 non-null   float64
 7   percentage        6732 non-null   float64
dtypes: float64(2), int64(3), str(3)
memory usage: 584.7 KB

In [125]:
Agg_user_df.rename(columns={
    "State": "state",
    "Year": "year",
    "Quarter": "quarter",
    "Registered_Users": "registered_users",
    "App_Opens": "app_opens"
}, inplace=True)

In [126]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             7128 non-null   str
 1   year              7128 non-null   str
 2   quarter           7128 non-null   int64
 3   registered_users  7128 non-null   int64
 4   app_opens         7128 non-null   int64
 5   brand             6732 non-null   str
 6   count             6732 non-null   float64
 7   percentage        6732 non-null   float64
dtypes: float64(2), int64(3), str(3)
memory usage: 584.7 KB

In [127]:
Agg_user_df

,state,year,quarter,registered_users,app_opens,brand,count,percentage
0,andaman-&-nicobar-islands,2018,1,6740,0,Xiaomi,1665.0,0.247033
1,andaman-&-nicobar-islands,2018,1,6740,0,Samsung,1445.0,0.214392
2,andaman-&-nicobar-islands,2018,1,6740,0,Vivo,982.0,0.145697
3,andaman-&-nicobar-islands,2018,1,6740,0,Oppo,501.0,0.074332
4,andaman-&-nicobar-islands,2018,1,6740,0,OnePlus,332.0,0.049258
...,...,...,...,...,...,...,...,...
7123,west-bengal,2023,4,30064546,1467442959,NaN,NaN,NaN
7124,west-bengal,2024,1,31306843,633526507,NaN,NaN,NaN
7125,west-bengal,2024,2,32540397,704276274,NaN,NaN,NaN
7126,west-bengal,2024,3,33612828,709864323,NaN,NaN,NaN
7127,west-bengal,2024,4,34750181,1994940763,NaN,NaN,NaN

In [128]:
Agg_user_df['state'] = Agg_user_df['state'].str.strip().str.title()

In [129]:
Agg_user_df

,state,year,quarter,registered_users,app_opens,brand,count,percentage
0,Andaman-&-Nicobar-Islands,2018,1,6740,0,Xiaomi,1665.0,0.247033
1,Andaman-&-Nicobar-Islands,2018,1,6740,0,Samsung,1445.0,0.214392
2,Andaman-&-Nicobar-Islands,2018,1,6740,0,Vivo,982.0,0.145697
3,Andaman-&-Nicobar-Islands,2018,1,6740,0,Oppo,501.0,0.074332
4,Andaman-&-Nicobar-Islands,2018,1,6740,0,OnePlus,332.0,0.049258
...,...,...,...,...,...,...,...,...
7123,West-Bengal,2023,4,30064546,1467442959,NaN,NaN,NaN
7124,West-Bengal,2024,1,31306843,633526507,NaN,NaN,NaN
7125,West-Bengal,2024,2,32540397,704276274,NaN,NaN,NaN
7126,West-Bengal,2024,3,33612828,709864323,NaN,NaN,NaN
7127,West-Bengal,2024,4,34750181,1994940763,NaN,NaN,NaN

## CHECK NULL VALUES IN app_opens column ##

In [130]:
Agg_user_df.isna().sum()

state                 0
year                  0
quarter               0
registered_users      0
app_opens             0
brand               396
count               396
percentage          396
dtype: int64

In [131]:
Agg_user_df['brand'].isna().sum()

np.int64(396)

In [132]:
Agg_user_df

,state,year,quarter,registered_users,app_opens,brand,count,percentage
0,Andaman-&-Nicobar-Islands,2018,1,6740,0,Xiaomi,1665.0,0.247033
1,Andaman-&-Nicobar-Islands,2018,1,6740,0,Samsung,1445.0,0.214392
2,Andaman-&-Nicobar-Islands,2018,1,6740,0,Vivo,982.0,0.145697
3,Andaman-&-Nicobar-Islands,2018,1,6740,0,Oppo,501.0,0.074332
4,Andaman-&-Nicobar-Islands,2018,1,6740,0,OnePlus,332.0,0.049258
...,...,...,...,...,...,...,...,...
7123,West-Bengal,2023,4,30064546,1467442959,NaN,NaN,NaN
7124,West-Bengal,2024,1,31306843,633526507,NaN,NaN,NaN
7125,West-Bengal,2024,2,32540397,704276274,NaN,NaN,NaN
7126,West-Bengal,2024,3,33612828,709864323,NaN,NaN,NaN
7127,West-Bengal,2024,4,34750181,1994940763,NaN,NaN,NaN

In [133]:
Agg_user_df['brand'].unique()

<ArrowStringArray>
[    'Xiaomi',    'Samsung',       'Vivo',       'Oppo',    'OnePlus',
     'Realme',      'Apple',   'Motorola',     'Lenovo',     'Huawei',
     'Others',      'Tecno',          nan,     'Gionee',    'Infinix',
       'Asus',   'Micromax', 'HMD Global',       'Lava',    'COOLPAD',
        'Lyf']
Length: 21, dtype: str

In [134]:
Agg_user_df['brand'].fillna('Unknown', inplace=True)

C:\Users\Harshad\AppData\Local\Temp\ipykernel_7440\2440215644.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  Agg_user_df['brand'].fillna('Unknown', inplace=True)

0        Xiaomi
1       Samsung
2          Vivo
3          Oppo
4       OnePlus
         ...
7123    Unknown
7124    Unknown
7125    Unknown
7126    Unknown
7127    Unknown
Name: brand, Length: 7128, dtype: str

In [135]:
Agg_user_df.isna().sum()

state                 0
year                  0
quarter               0
registered_users      0
app_opens             0
brand               396
count               396
percentage          396
dtype: int64

In [136]:
Agg_user_df['brand'] = Agg_user_df['brand'].fillna('Unknown')
Agg_user_df['count'] = Agg_user_df['count'].fillna(0)
Agg_user_df['percentage'] = Agg_user_df['percentage'].fillna(0)

In [137]:
Agg_user_df.isna().sum()

state               0
year                0
quarter             0
registered_users    0
app_opens           0
brand               0
count               0
percentage          0
dtype: int64

In [138]:
Agg_user_df

,state,year,quarter,registered_users,app_opens,brand,count,percentage
0,Andaman-&-Nicobar-Islands,2018,1,6740,0,Xiaomi,1665.0,0.247033
1,Andaman-&-Nicobar-Islands,2018,1,6740,0,Samsung,1445.0,0.214392
2,Andaman-&-Nicobar-Islands,2018,1,6740,0,Vivo,982.0,0.145697
3,Andaman-&-Nicobar-Islands,2018,1,6740,0,Oppo,501.0,0.074332
4,Andaman-&-Nicobar-Islands,2018,1,6740,0,OnePlus,332.0,0.049258
...,...,...,...,...,...,...,...,...
7123,West-Bengal,2023,4,30064546,1467442959,Unknown,0.0,0.000000
7124,West-Bengal,2024,1,31306843,633526507,Unknown,0.0,0.000000
7125,West-Bengal,2024,2,32540397,704276274,Unknown,0.0,0.000000
7126,West-Bengal,2024,3,33612828,709864323,Unknown,0.0,0.000000
7127,West-Bengal,2024,4,34750181,1994940763,Unknown,0.0,0.000000

In [139]:
Agg_user_df[~Agg_user_df['quarter'].isin([1,2,3,4])]
Agg_user_df

,state,year,quarter,registered_users,app_opens,brand,count,percentage
0,Andaman-&-Nicobar-Islands,2018,1,6740,0,Xiaomi,1665.0,0.247033
1,Andaman-&-Nicobar-Islands,2018,1,6740,0,Samsung,1445.0,0.214392
2,Andaman-&-Nicobar-Islands,2018,1,6740,0,Vivo,982.0,0.145697
3,Andaman-&-Nicobar-Islands,2018,1,6740,0,Oppo,501.0,0.074332
4,Andaman-&-Nicobar-Islands,2018,1,6740,0,OnePlus,332.0,0.049258
...,...,...,...,...,...,...,...,...
7123,West-Bengal,2023,4,30064546,1467442959,Unknown,0.0,0.000000
7124,West-Bengal,2024,1,31306843,633526507,Unknown,0.0,0.000000
7125,West-Bengal,2024,2,32540397,704276274,Unknown,0.0,0.000000
7126,West-Bengal,2024,3,33612828,709864323,Unknown,0.0,0.000000
7127,West-Bengal,2024,4,34750181,1994940763,Unknown,0.0,0.000000

In [140]:
Agg_user_df[(Agg_user_df['year'].astype(int) < 2018) | (Agg_user_df['year'].astype(int) > 2024)]

Empty DataFrame
Columns: [state, year, quarter, registered_users, app_opens, brand, count, percentage]
Index: []

In [141]:
Agg_user_df.groupby(['state','year','quarter'])['count'].sum()

state                      year  quarter
Andaman-&-Nicobar-Islands  2018  1           6740.0
                                 2           9405.0
                                 3          12149.0
                                 4          15222.0
                           2019  1          18596.0
                                             ...
West-Bengal                2023  4              0.0
                           2024  1              0.0
                                 2              0.0
                                 3              0.0
                                 4              0.0
Name: count, Length: 1008, dtype: float64

In [142]:
Agg_user_df.groupby(['state','year','quarter'])['percentage'].sum()

state                      year  quarter
Andaman-&-Nicobar-Islands  2018  1          1.0
                                 2          1.0
                                 3          1.0
                                 4          1.0
                           2019  1          1.0
                                           ...
West-Bengal                2023  4          0.0
                           2024  1          0.0
                                 2          0.0
                                 3          0.0
                                 4          0.0
Name: percentage, Length: 1008, dtype: float64

## TO CHECK OUTLIERS ON app opens with registered users 
“In West Bengal, during Q4 of 2024, App Opens = 1,994,940,763. This value is much higher compared to the other quarters, so it will be flagged as an outlier.” ###

In [143]:
Q1 = Agg_user_df['app_opens'].quantile(0.25)
Q3 = Agg_user_df['app_opens'].quantile(0.75)
IQR = Q3 - Q1

outliers = Agg_user_df[
    (Agg_user_df['app_opens'] < (Q1 - 1.5 * IQR)) |
    (Agg_user_df['app_opens'] > (Q3 + 1.5 * IQR))
]
print(outliers)

               state  year  quarter  registered_users   app_opens    brand  \
286   Andhra-Pradesh  2020        1          13022060   486513773   Xiaomi
287   Andhra-Pradesh  2020        1          13022060   486513773  Samsung
288   Andhra-Pradesh  2020        1          13022060   486513773     Vivo
289   Andhra-Pradesh  2020        1          13022060   486513773     Oppo
290   Andhra-Pradesh  2020        1          13022060   486513773   Realme
...              ...   ...      ...               ...         ...      ...
7123     West-Bengal  2023        4          30064546  1467442959  Unknown
7124     West-Bengal  2024        1          31306843   633526507  Unknown
7125     West-Bengal  2024        2          32540397   704276274  Unknown
7126     West-Bengal  2024        3          33612828   709864323  Unknown
7127     West-Bengal  2024        4          34750181  1994940763  Unknown

          count  percentage
286   3307542.0    0.253995
287   2622762.0    0.201409
288   2165012.0    0.166257
289   1387060.0    0.106516
290    960418.0    0.073753
...         ...         ...
7123        0.0    0.000000
7124        0.0    0.000000
7125        0.0    0.000000
7126        0.0    0.000000
7127        0.0    0.000000

[914 rows x 8 columns]

In [144]:
median_value = Agg_user_df['app_opens'].median()
print(median_value)

7162734.0

In [145]:
Agg_user_df.describe()

           quarter  registered_users     app_opens         count   percentage
count  7128.000000      7.128000e+03  7.128000e+03  7.128000e+03  7128.000000
mean      2.424242      6.098127e+06  1.860901e+08  4.854553e+05     0.085859
std       1.137958      8.822868e+06  4.340965e+08  1.057863e+06     0.083683
min       1.000000      5.010000e+02  0.000000e+00  0.000000e+00     0.000000
25%       1.000000      2.056860e+05  0.000000e+00  5.886000e+03     0.018321
50%       2.000000      2.133804e+06  7.162734e+06  6.577150e+04     0.049423
75%       3.000000      8.972299e+06  1.765590e+08  4.160462e+05     0.138776
max       4.000000      7.180780e+07  5.335171e+09  1.134094e+07     0.478367

In [146]:

Q1 = Agg_user_df['app_opens'].quantile(0.25)
Q3 = Agg_user_df['app_opens'].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR


Agg_user_df['is_data_issue'] = (
    ((Agg_user_df['registered_users'] > 0) & (Agg_user_df['app_opens'] == 0))   # Rule 1
    |
    (Agg_user_df['app_opens'] < Agg_user_df['registered_users'])                # Rule 2
    |
    ((Agg_user_df['app_opens'] < lower_limit) | (Agg_user_df['app_opens'] > upper_limit))  # Rule 3
)

print(Agg_user_df[['state','year','quarter','app_opens','is_data_issue']])

                          state  year  quarter   app_opens  is_data_issue
0     Andaman-&-Nicobar-Islands  2018        1           0           True
1     Andaman-&-Nicobar-Islands  2018        1           0           True
2     Andaman-&-Nicobar-Islands  2018        1           0           True
3     Andaman-&-Nicobar-Islands  2018        1           0           True
4     Andaman-&-Nicobar-Islands  2018        1           0           True
...                         ...   ...      ...         ...            ...
7123                West-Bengal  2023        4  1467442959           True
7124                West-Bengal  2024        1   633526507           True
7125                West-Bengal  2024        2   704276274           True
7126                West-Bengal  2024        3   709864323           True
7127                West-Bengal  2024        4  1994940763           True

[7128 rows x 5 columns]

In [147]:
Agg_user_df

,state,year,quarter,registered_users,app_opens,brand,count,percentage,is_data_issue
0,Andaman-&-Nicobar-Islands,2018,1,6740,0,Xiaomi,1665.0,0.247033,True
1,Andaman-&-Nicobar-Islands,2018,1,6740,0,Samsung,1445.0,0.214392,True
2,Andaman-&-Nicobar-Islands,2018,1,6740,0,Vivo,982.0,0.145697,True
3,Andaman-&-Nicobar-Islands,2018,1,6740,0,Oppo,501.0,0.074332,True
4,Andaman-&-Nicobar-Islands,2018,1,6740,0,OnePlus,332.0,0.049258,True
...,...,...,...,...,...,...,...,...,...
7123,West-Bengal,2023,4,30064546,1467442959,Unknown,0.0,0.000000,True
7124,West-Bengal,2024,1,31306843,633526507,Unknown,0.0,0.000000,True
7125,West-Bengal,2024,2,32540397,704276274,Unknown,0.0,0.000000,True
7126,West-Bengal,2024,3,33612828,709864323,Unknown,0.0,0.000000,True
7127,West-Bengal,2024,4,34750181,1994940763,Unknown,0.0,0.000000,True

In [148]:
Agg_user_df.shape

(7128, 9)

In [149]:
Agg_user_df[Agg_user_df['state'] == 'Andaman-&-Nicobar-Islands']

,state,year,quarter,registered_users,app_opens,brand,count,percentage,is_data_issue
0,Andaman-&-Nicobar-Islands,2018,1,6740,0,Xiaomi,1665.0,0.247033,True
1,Andaman-&-Nicobar-Islands,2018,1,6740,0,Samsung,1445.0,0.214392,True
2,Andaman-&-Nicobar-Islands,2018,1,6740,0,Vivo,982.0,0.145697,True
3,Andaman-&-Nicobar-Islands,2018,1,6740,0,Oppo,501.0,0.074332,True
4,Andaman-&-Nicobar-Islands,2018,1,6740,0,OnePlus,332.0,0.049258,True
...,...,...,...,...,...,...,...,...,...
193,Andaman-&-Nicobar-Islands,2023,4,103978,9845960,Unknown,0.0,0.000000,False
194,Andaman-&-Nicobar-Islands,2024,1,108411,28538751,Unknown,0.0,0.000000,False
195,Andaman-&-Nicobar-Islands,2024,2,112687,16876883,Unknown,0.0,0.000000,False
196,Andaman-&-Nicobar-Islands,2024,3,172473,19554846,Unknown,0.0,0.000000,False
197,Andaman-&-Nicobar-Islands,2024,4,178788,18691683,Unknown,0.0,0.000000,False

In [150]:
Agg_user_df['count']

0       1665.0
1       1445.0
2        982.0
3        501.0
4        332.0
         ...
7123       0.0
7124       0.0
7125       0.0
7126       0.0
7127       0.0
Name: count, Length: 7128, dtype: float64

In [151]:
# Rule: registered_users > 0 but app_opens == 0 then  data issue
Agg_user_df['is_data_issue'] = (
    (Agg_user_df['registered_users'] > 0) & 
    (Agg_user_df['app_opens'] == 0)
)

print(Agg_user_df[['state','year','quarter','registered_users','app_opens','is_data_issue']])

                          state  year  quarter  registered_users   app_opens  \
0     Andaman-&-Nicobar-Islands  2018        1              6740           0
1     Andaman-&-Nicobar-Islands  2018        1              6740           0
2     Andaman-&-Nicobar-Islands  2018        1              6740           0
3     Andaman-&-Nicobar-Islands  2018        1              6740           0
4     Andaman-&-Nicobar-Islands  2018        1              6740           0
...                         ...   ...      ...               ...         ...
7123                West-Bengal  2023        4          30064546  1467442959
7124                West-Bengal  2024        1          31306843   633526507
7125                West-Bengal  2024        2          32540397   704276274
7126                West-Bengal  2024        3          33612828   709864323
7127                West-Bengal  2024        4          34750181  1994940763

      is_data_issue
0              True
1              True
2              True
3              True
4              True
...             ...
7123          False
7124          False
7125          False
7126          False
7127          False

[7128 rows x 6 columns]

## Final Dataset Validation ##

In [152]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             7128 non-null   str
 1   year              7128 non-null   str
 2   quarter           7128 non-null   int64
 3   registered_users  7128 non-null   int64
 4   app_opens         7128 non-null   int64
 5   brand             7128 non-null   str
 6   count             7128 non-null   float64
 7   percentage        7128 non-null   float64
 8   is_data_issue     7128 non-null   bool
dtypes: bool(1), float64(2), int64(3), str(3)
memory usage: 594.4 KB

In [165]:
Agg_user_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

In [154]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             7128 non-null   str
 1   year              7128 non-null   str
 2   quarter           7128 non-null   int64
 3   registered_users  7128 non-null   int64
 4   app_opens         7128 non-null   int64
 5   brand             7128 non-null   str
 6   count             7128 non-null   float64
 7   percentage        7128 non-null   float64
 8   is_data_issue     7128 non-null   bool
dtypes: bool(1), float64(2), int64(3), str(3)
memory usage: 594.4 KB

In [155]:
Agg_user_df["year"] = Agg_user_df["year"].astype("int32")

In [156]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             7128 non-null   str
 1   year              7128 non-null   int32
 2   quarter           7128 non-null   int64
 3   registered_users  7128 non-null   int64
 4   app_opens         7128 non-null   int64
 5   brand             7128 non-null   str
 6   count             7128 non-null   float64
 7   percentage        7128 non-null   float64
 8   is_data_issue     7128 non-null   bool
dtypes: bool(1), float64(2), int32(1), int64(3), str(2)
memory usage: 538.7 KB

In [157]:
Agg_user_df["brand"] = Agg_user_df["brand"].astype("category")

In [158]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             7128 non-null   str
 1   year              7128 non-null   int32
 2   quarter           7128 non-null   int64
 3   registered_users  7128 non-null   int64
 4   app_opens         7128 non-null   int64
 5   brand             7128 non-null   category
 6   count             7128 non-null   float64
 7   percentage        7128 non-null   float64
 8   is_data_issue     7128 non-null   bool
dtypes: bool(1), category(1), float64(2), int32(1), int64(3), str(1)
memory usage: 448.7 KB

In [159]:
Agg_user_df['count'] = Agg_user_df['count'].astype("int64")

In [164]:
Agg_user_df['brand']

0        Xiaomi
1       Samsung
2          Vivo
3          Oppo
4       OnePlus
         ...
7123    Unknown
7124    Unknown
7125    Unknown
7126    Unknown
7127    Unknown
Name: brand, Length: 7128, dtype: category
Categories (21, str): ['Apple', 'Asus', 'COOLPAD', 'Gionee', ..., 'Tecno', 'Unknown', 'Vivo', 'Xiaomi']

In [160]:
Agg_user_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7128 entries, 0 to 7127
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             7128 non-null   str
 1   year              7128 non-null   int32
 2   quarter           7128 non-null   int64
 3   registered_users  7128 non-null   int64
 4   app_opens         7128 non-null   int64
 5   brand             7128 non-null   category
 6   count             7128 non-null   int64
 7   percentage        7128 non-null   float64
 8   is_data_issue     7128 non-null   bool
dtypes: bool(1), category(1), float64(1), int32(1), int64(4), str(1)
memory usage: 448.7 KB

## CREATE CONNECTION DATABASE AND CREATE TABLE ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS user_data (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER,
        registered_users BIGINT,
        app_opens BIGINT,
        brand VARCHAR(255) NOT NULL,
        count BIGINT,
        percentage DECIMAL(5,4)
    );
""")

conn.commit()
cur.close()
conn.close()
print("Table 'user_data' created successfully")

Table 'user_data' created successfully

## ADDING is_data_issue column in table ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    ALTER TABLE user_data 
    ADD COLUMN is_data_issue BOOLEAN;
""")

conn.commit()
cur.close()
conn.close()
print("COLUMN Added successfully")

COLUMN Added successfully

## INSERT DATA INTO USER_DATA TABLE ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in Agg_user_df.iterrows():
    cur.execute(
        """
        INSERT INTO user_data (
            state,
            year,
            quarter,
            registered_users,
            app_opens,
            brand,
            count,
            percentage,
            is_data_issue
        )
        VALUES (%s, %s, %s, %s, %s, %s,%s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["registered_users"],
            row["app_opens"],
            row["brand"],
            row["count"],
            row["percentage"],
            row["is_data_issue"]
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()
cur.execute("""ALTER TABLE user_data
RENAME TO user_agg;""")


conn.commit()
cur.close()
conn.close()
print("Table name changed to user_agg successfully")

Table name changed to user_agg successfully