# Aggregated Insurance data analysis #

In [1]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\aggregated\\insurance\\country\\india\\state\\"
Agg_state_list=os.listdir(path)
Agg_state_list
clm={'state':[], 'year':[],'quarter':[],'data_from':[], 'data_to':[], 'payment_category':[], 'total_count':[], 'total_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"\\"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"\\"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            data_from = D['data']['from']
            data_to = D['data']['to']
            for z in D['data']['transactionData']:
              payment_category = z['name']
              for m in z['paymentInstruments']:
                count=m['count']
                amount=m['amount']
                clm['data_from'].append(data_from)
                clm['data_to'].append(data_to)
                clm['payment_category'].append(payment_category)
                clm['total_count'].append(count)
                clm['total_amount'].append(amount)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

agg_insurance_df=pd.DataFrame(clm)

agg_insurance_df

,state,year,quarter,data_from,data_to,payment_category,total_count,total_amount
0,andaman-&-nicobar-islands,2020,2,1585679400000,1593282600000,Insurance,6,1360.0
1,andaman-&-nicobar-islands,2020,3,1593541800000,1601231400000,Insurance,41,15380.0
2,andaman-&-nicobar-islands,2020,4,1601490600000,1609093800000,Insurance,124,157975.0
3,andaman-&-nicobar-islands,2021,1,1609439400000,1616869800000,Insurance,225,244266.0
4,andaman-&-nicobar-islands,2021,2,1617215400000,1624818600000,Insurance,137,181504.0
...,...,...,...,...,...,...,...,...
677,west-bengal,2023,4,1696098600000,1703701800000,Insurance,72712,100365562.0
678,west-bengal,2024,1,1704047400000,1711564200000,Insurance,79576,104987909.0
679,west-bengal,2024,2,1711909800000,1719513000000,Insurance,67048,89476633.0
680,west-bengal,2024,3,1719792000000,1727481600000,Insurance,77158,107451766.0
681,west-bengal,2024,4,1727740800000,1735344000000,Insurance,91719,120602777.0

In [2]:
agg_insurance_df.shape

(682, 8)

In [3]:
agg_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    str
 1   year              682 non-null    str
 2   quarter           682 non-null    int64
 3   data_from         682 non-null    int64
 4   data_to           682 non-null    int64
 5   payment_category  682 non-null    str
 6   total_count       682 non-null    int64
 7   total_amount      682 non-null    float64
dtypes: float64(1), int64(4), str(3)
memory usage: 58.3 KB

In [4]:
q2_andaman = agg_insurance_df[
    (agg_insurance_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (agg_insurance_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'total_count', 'total_amount']])

    year  quarter  total_count  total_amount
0   2020        2            6        1360.0
4   2021        2          137      181504.0
8   2022        2          501      779740.0
12  2023        2          768     1233395.0
16  2024        2         1097     1744694.0

In [5]:
agg_insurance_df.describe()

          quarter     data_from       data_to    total_count  total_amount
count  682.000000  6.820000e+02  6.820000e+02     682.000000  6.820000e+02
mean     2.577713  1.656865e+12  1.664459e+12   21283.998534  2.934836e+07
std      1.092211  4.316505e+10  4.317010e+10   31503.745791  4.763085e+07
min      1.000000  1.585679e+12  1.593283e+12       4.000000  1.199000e+03
25%      2.000000  1.617215e+12  1.624819e+12     607.750000  8.211475e+05
50%      3.000000  1.656614e+12  1.664303e+12    6679.500000  6.675645e+06
75%      4.000000  1.696099e+12  1.703702e+12   29790.500000  3.730685e+07
max      4.000000  1.727741e+12  1.735344e+12  183532.000000  3.058618e+08

In [6]:
agg_insurance_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [7]:
agg_insurance_df.isna().sum()

state               0
year                0
quarter             0
data_from           0
data_to             0
payment_category    0
total_count         0
total_amount        0
dtype: int64

In [8]:
agg_insurance_df['state'].isna().sum()

np.int64(0)

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [9]:
agg_insurance_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [10]:
agg_insurance_df['state'].value_counts()

state
andaman-&-nicobar-islands             19
andhra-pradesh                        19
arunachal-pradesh                     19
assam                                 19
bihar                                 19
chandigarh                            19
chhattisgarh                          19
dadra-&-nagar-haveli-&-daman-&-diu    19
delhi                                 19
goa                                   19
gujarat                               19
haryana                               19
himachal-pradesh                      19
jammu-&-kashmir                       19
jharkhand                             19
karnataka                             19
kerala                                19
ladakh                                19
madhya-pradesh                        19
maharashtra                           19
manipur                               19
meghalaya                             19
mizoram                               19
nagaland                              19
odisha                                19
puducherry                            19
punjab                                19
rajasthan                             19
sikkim                                19
tamil-nadu                            19
telangana                             19
tripura                               19
uttar-pradesh                         19
uttarakhand                           19
west-bengal                           19
lakshadweep                           17
Name: count, dtype: int64

In [11]:
agg_insurance_df['state'] = agg_insurance_df['state'].str.strip().str.title()

In [12]:
agg_insurance_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Payment Category Column Unique Values ##

In [13]:
agg_insurance_df['payment_category'].unique()

<ArrowStringArray>
['Insurance']
Length: 1, dtype: str

## VALIDATE FINAL DATASET INTEGRITY ##

In [14]:
agg_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    str
 1   year              682 non-null    str
 2   quarter           682 non-null    int64
 3   data_from         682 non-null    int64
 4   data_to           682 non-null    int64
 5   payment_category  682 non-null    str
 6   total_count       682 non-null    int64
 7   total_amount      682 non-null    float64
dtypes: float64(1), int64(4), str(3)
memory usage: 58.3 KB

In [15]:
agg_insurance_df['year'] = agg_insurance_df['year'].astype('int32')
agg_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    str
 1   year              682 non-null    int32
 2   quarter           682 non-null    int64
 3   data_from         682 non-null    int64
 4   data_to           682 non-null    int64
 5   payment_category  682 non-null    str
 6   total_count       682 non-null    int64
 7   total_amount      682 non-null    float64
dtypes: float64(1), int32(1), int64(4), str(2)
memory usage: 53.0 KB

In [16]:
agg_insurance_df

,state,year,quarter,data_from,data_to,payment_category,total_count,total_amount
0,Andaman-&-Nicobar-Islands,2020,2,1585679400000,1593282600000,Insurance,6,1360.0
1,Andaman-&-Nicobar-Islands,2020,3,1593541800000,1601231400000,Insurance,41,15380.0
2,Andaman-&-Nicobar-Islands,2020,4,1601490600000,1609093800000,Insurance,124,157975.0
3,Andaman-&-Nicobar-Islands,2021,1,1609439400000,1616869800000,Insurance,225,244266.0
4,Andaman-&-Nicobar-Islands,2021,2,1617215400000,1624818600000,Insurance,137,181504.0
...,...,...,...,...,...,...,...,...
677,West-Bengal,2023,4,1696098600000,1703701800000,Insurance,72712,100365562.0
678,West-Bengal,2024,1,1704047400000,1711564200000,Insurance,79576,104987909.0
679,West-Bengal,2024,2,1711909800000,1719513000000,Insurance,67048,89476633.0
680,West-Bengal,2024,3,1719792000000,1727481600000,Insurance,77158,107451766.0
681,West-Bengal,2024,4,1727740800000,1735344000000,Insurance,91719,120602777.0

In [17]:
## Converting Unix date to sql date format
# agg_insurance_df['data_from'] = pd.to_datetime(agg_insurance_df['data_from'], unit='ms',utc=True)
# agg_insurance_df['data_to'] = pd.to_datetime(agg_insurance_df['data_to'], unit='ms',utc=True)

agg_insurance_df['data_from'] = (
    pd.to_datetime(agg_insurance_df['data_from'], unit='ms', utc=True)
      .dt.tz_convert('Asia/Kolkata')
      .dt.date
)

agg_insurance_df['data_to'] = (
    pd.to_datetime(agg_insurance_df['data_to'], unit='ms', utc=True)
      .dt.tz_convert('Asia/Kolkata')
      .dt.date
)

agg_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    str
 1   year              682 non-null    int32
 2   quarter           682 non-null    int64
 3   data_from         682 non-null    object
 4   data_to           682 non-null    object
 5   payment_category  682 non-null    str
 6   total_count       682 non-null    int64
 7   total_amount      682 non-null    float64
dtypes: float64(1), int32(1), int64(2), object(2), str(2)
memory usage: 53.0+ KB

In [66]:
agg_insurance_df

,state,year,quarter,data_from,data_to,payment_category,total_count,total_amount
0,Andaman-&-Nicobar-Islands,2020,2,2020-04-01,2020-06-28,Insurance,6,1360.0
1,Andaman-&-Nicobar-Islands,2020,3,2020-07-01,2020-09-28,Insurance,41,15380.0
2,Andaman-&-Nicobar-Islands,2020,4,2020-10-01,2020-12-28,Insurance,124,157975.0
3,Andaman-&-Nicobar-Islands,2021,1,2021-01-01,2021-03-28,Insurance,225,244266.0
4,Andaman-&-Nicobar-Islands,2021,2,2021-04-01,2021-06-28,Insurance,137,181504.0
...,...,...,...,...,...,...,...,...
677,West-Bengal,2023,4,2023-10-01,2023-12-28,Insurance,72712,100365562.0
678,West-Bengal,2024,1,2024-01-01,2024-03-28,Insurance,79576,104987909.0
679,West-Bengal,2024,2,2024-04-01,2024-06-28,Insurance,67048,89476633.0
680,West-Bengal,2024,3,2024-07-01,2024-09-28,Insurance,77158,107451766.0
681,West-Bengal,2024,4,2024-10-01,2024-12-28,Insurance,91719,120602777.0

In [18]:
agg_insurance_df['data_from'] = agg_insurance_df['data_from'].astype('datetime64[ns]')
agg_insurance_df['data_to'] = agg_insurance_df['data_to'].astype('datetime64[ns]')
agg_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    str
 1   year              682 non-null    int32
 2   quarter           682 non-null    int64
 3   data_from         682 non-null    datetime64[ns]
 4   data_to           682 non-null    datetime64[ns]
 5   payment_category  682 non-null    str
 6   total_count       682 non-null    int64
 7   total_amount      682 non-null    float64
dtypes: datetime64[ns](2), float64(1), int32(1), int64(2), str(2)
memory usage: 53.0 KB

## Create Connection and database ##

In [ ]:
import psycopg2

DB_NAME = "smart_pay"
conn_params = {
    "host": "localhost",
    "database": "postgres",
    "user": "postgres",
    "password": "",
}

conn = psycopg2.connect(**conn_params)
conn.autocommit = True
cur = conn.cursor()

cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,))
exists = cur.fetchone()

if not exists:
    cur.execute(f'CREATE DATABASE "{DB_NAME}"')
    print(f"Database '{DB_NAME}' created successfully")
else:
    print(f"Database '{DB_NAME}' already exists")

cur.close()
conn.close()

Database 'smart_pay' already exists

## Create insurance_agg Table In Database ##

In [20]:
agg_insurance_df

,state,year,quarter,data_from,data_to,payment_category,total_count,total_amount
0,Andaman-&-Nicobar-Islands,2020,2,2020-04-01,2020-06-28,Insurance,6,1360.0
1,Andaman-&-Nicobar-Islands,2020,3,2020-07-01,2020-09-28,Insurance,41,15380.0
2,Andaman-&-Nicobar-Islands,2020,4,2020-10-01,2020-12-28,Insurance,124,157975.0
3,Andaman-&-Nicobar-Islands,2021,1,2021-01-01,2021-03-28,Insurance,225,244266.0
4,Andaman-&-Nicobar-Islands,2021,2,2021-04-01,2021-06-28,Insurance,137,181504.0
...,...,...,...,...,...,...,...,...
677,West-Bengal,2023,4,2023-10-01,2023-12-28,Insurance,72712,100365562.0
678,West-Bengal,2024,1,2024-01-01,2024-03-28,Insurance,79576,104987909.0
679,West-Bengal,2024,2,2024-04-01,2024-06-28,Insurance,67048,89476633.0
680,West-Bengal,2024,3,2024-07-01,2024-09-28,Insurance,77158,107451766.0
681,West-Bengal,2024,4,2024-10-01,2024-12-28,Insurance,91719,120602777.0

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS insurance_agg (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,
        data_from TIMESTAMP NOT NULL,
        data_to TIMESTAMP NOT NULL,
        payment_category VARCHAR(255),
        total_count BIGINT,
        total_amount NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.insurance_agg')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'insurance_agg' created successfully")

Table exists in PostgreSQL: insurance_agg
Table 'insurance_agg' created successfully

## Inserting Data from Data Frame to Insurance_data Table ##

In [22]:
agg_insurance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    str
 1   year              682 non-null    int32
 2   quarter           682 non-null    int64
 3   data_from         682 non-null    datetime64[ns]
 4   data_to           682 non-null    datetime64[ns]
 5   payment_category  682 non-null    str
 6   total_count       682 non-null    int64
 7   total_amount      682 non-null    float64
dtypes: datetime64[ns](2), float64(1), int32(1), int64(2), str(2)
memory usage: 53.0 KB

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in agg_insurance_df.iterrows():
    cur.execute(
        """
        INSERT INTO insurance_agg (
            state,
            year,
            quarter,
            data_from,
            data_to,
            payment_category,
            total_count,
            total_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["data_from"],
            row["data_to"],
            row["payment_category"],
            row["total_count"],
            row["total_amount"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully