# Top Insurance Pincodes data analysis #

In [12]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\top\\insurance\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
clm={'state':[], 'year':[],'quarter':[],'pincodes':[], 'insurance_count':[], 'insurance_amount':[] }

for i in top_state_list:
    p_i=path+i+"\\"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"\\"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['pincodes']:
                pincodes = z['entityName']
                insurance_count=z['metric']['count']
                insurance_amount=z['metric']['amount']
                clm['pincodes'].append(pincodes)
                clm['insurance_count'].append(insurance_count)
                clm['insurance_amount'].append(insurance_amount)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

top_insurance_pincodes_df=pd.DataFrame(clm)

top_insurance_pincodes_df

,state,year,quarter,pincodes,insurance_count,insurance_amount
0,andaman-&-nicobar-islands,2020,2,744301,3,565.0
1,andaman-&-nicobar-islands,2020,2,744104,2,513.0
2,andaman-&-nicobar-islands,2020,2,744101,1,282.0
3,andaman-&-nicobar-islands,2020,3,744112,9,3432.0
4,andaman-&-nicobar-islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,west-bengal,2024,4,711101,713,750354.0
6664,west-bengal,2024,4,700091,642,969634.0
6665,west-bengal,2024,4,700150,627,761501.0
6666,west-bengal,2024,4,700039,619,787836.0
6667,west-bengal,2024,4,700156,574,888613.0

In [13]:
len(D['data']['pincodes'])

10

In [14]:
len(top_insurance_pincodes_df['pincodes'])

6668

In [15]:
top_insurance_pincodes_df.shape

(6668, 6)

In [16]:
top_insurance_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6668 entries, 0 to 6667
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             6668 non-null   str
 1   year              6668 non-null   str
 2   quarter           6668 non-null   int64
 3   pincodes          6665 non-null   str
 4   insurance_count   6668 non-null   int64
 5   insurance_amount  6668 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 444.4 KB

In [18]:
q2_andaman = top_insurance_pincodes_df[
    (top_insurance_pincodes_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (top_insurance_pincodes_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'pincodes', 'insurance_amount']])

     year  quarter pincodes  insurance_amount
0    2020        2   744301             565.0
1    2020        2   744104             513.0
2    2020        2   744101             282.0
33   2021        2   744103           33716.0
34   2021        2   744101           19787.0
35   2021        2   744105           17163.0
36   2021        2   744102           10326.0
37   2021        2   744204           10557.0
38   2021        2   744107           11459.0
39   2021        2   744202            9766.0
40   2021        2   744104            8889.0
41   2021        2   744205           12669.0
42   2021        2   744210            9430.0
73   2022        2   744103          156861.0
74   2022        2   744101          121168.0
75   2022        2   744105          137418.0
76   2022        2   744102           58453.0
77   2022        2   744104           32107.0
78   2022        2   744107           52244.0
79   2022        2   744211           25543.0
80   2022        2   744112           24391.0
81   2022        2   744301           28331.0
82   2022        2   744202           20817.0
113  2023        2   744103          341853.0
114  2023        2   744105          255069.0
115  2023        2   744101          189989.0
116  2023        2   744102          101875.0
117  2023        2   744104           34345.0
118  2023        2   744301           41299.0
119  2023        2   744207           43459.0
120  2023        2   744112           20427.0
121  2023        2   744107           24693.0
122  2023        2   744205           31404.0
153  2024        2   744103          438830.0
154  2024        2   744105          276393.0
155  2024        2   744101          251503.0
156  2024        2   744102          203605.0
157  2024        2   744112           77583.0
158  2024        2   744104           91213.0
159  2024        2   744107           52311.0
160  2024        2   744202           41210.0
161  2024        2   744211           43685.0
162  2024        2   744302           37685.0

In [19]:
top_insurance_pincodes_df.describe()

           quarter  insurance_count  insurance_amount
count  6668.000000      6668.000000      6.668000e+03
mean      2.581284       345.025345      4.442041e+05
std       1.092603       477.681141      6.888540e+05
min       1.000000         1.000000      3.100000e+01
25%       2.000000        33.000000      3.676025e+04
50%       3.000000       159.000000      1.644650e+05
75%       4.000000       447.000000      5.332610e+05
max       4.000000      3947.000000      5.740577e+06

In [20]:
top_insurance_pincodes_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [21]:
top_insurance_pincodes_df.isna().sum()

state               0
year                0
quarter             0
pincodes            3
insurance_count     0
insurance_amount    0
dtype: int64

In [22]:
top_insurance_pincodes_df['pincodes'].isna().sum()

np.int64(3)

In [23]:
top_insurance_pincodes_df['pincodes']

0       744301
1       744104
2       744101
3       744112
4       744105
         ...
6663    711101
6664    700091
6665    700150
6666    700039
6667    700156
Name: pincodes, Length: 6668, dtype: str

In [24]:
top_insurance_pincodes_df[top_insurance_pincodes_df['pincodes'].isna()]

       state  year  quarter pincodes  insurance_count  insurance_amount
3199  ladakh  2020        3      NaN                1             281.0
3207  ladakh  2020        4      NaN                1             658.0
3284  ladakh  2022        4      NaN                8           16020.0

In [25]:
top_insurance_pincodes_df['pincodes'] = top_insurance_pincodes_df['pincodes'].fillna('Unknown')

In [26]:
top_insurance_pincodes_df[top_insurance_pincodes_df['pincodes'].isna()]

Empty DataFrame
Columns: [state, year, quarter, pincodes, insurance_count, insurance_amount]
Index: []

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [27]:
top_insurance_pincodes_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [28]:
top_insurance_pincodes_df['state'].value_counts()

state
andhra-pradesh                        190
arunachal-pradesh                     190
assam                                 190
bihar                                 190
chandigarh                            190
chhattisgarh                          190
delhi                                 190
goa                                   190
gujarat                               190
haryana                               190
himachal-pradesh                      190
jammu-&-kashmir                       190
jharkhand                             190
karnataka                             190
kerala                                190
madhya-pradesh                        190
maharashtra                           190
manipur                               190
meghalaya                             190
nagaland                              190
odisha                                190
puducherry                            190
punjab                                190
rajasthan                             190
sikkim                                190
tamil-nadu                            190
telangana                             190
tripura                               190
uttar-pradesh                         190
uttarakhand                           190
west-bengal                           190
mizoram                               189
ladakh                                185
andaman-&-nicobar-islands             183
dadra-&-nagar-haveli-&-daman-&-diu    150
lakshadweep                            71
Name: count, dtype: int64

In [29]:
top_insurance_pincodes_df['state'] = top_insurance_pincodes_df['state'].str.strip().str.title()

In [30]:
top_insurance_pincodes_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Districts Column Unique Values ##

In [31]:
top_insurance_pincodes_df['pincodes'].unique()

<ArrowStringArray>
['744301', '744104', '744101', '744112', '744105', '744206', '744107',
 '744103', '744302', '744211',
 ...
 '712223', '700078', '713102', '700036', '711202', '713101', '700014',
 '700052', '721301', '734001']
Length: 900, dtype: str

In [32]:
top_insurance_pincodes_df[top_insurance_pincodes_df['pincodes'] == '744103']

,state,year,quarter,pincodes,insurance_count,insurance_amount
8,Andaman-&-Nicobar-Islands,2020,3,744103,3,947.0
15,Andaman-&-Nicobar-Islands,2020,4,744103,18,24904.0
24,Andaman-&-Nicobar-Islands,2021,1,744103,35,39985.0
33,Andaman-&-Nicobar-Islands,2021,2,744103,36,33716.0
44,Andaman-&-Nicobar-Islands,2021,3,744103,44,53909.0
55,Andaman-&-Nicobar-Islands,2021,4,744103,133,168668.0
63,Andaman-&-Nicobar-Islands,2022,1,744103,174,226181.0
73,Andaman-&-Nicobar-Islands,2022,2,744103,97,156861.0
83,Andaman-&-Nicobar-Islands,2022,3,744103,151,198569.0
93,Andaman-&-Nicobar-Islands,2022,4,744103,199,299036.0
103,Andaman-&-Nicobar-Islands,2023,1,744103,236,286594.0
113,Andaman-&-Nicobar-Islands,2023,2,744103,171,341853.0
123,Andaman-&-Nicobar-Islands,2023,3,744103,191,306744.0
133,Andaman-&-Nicobar-Islands,2023,4,744103,268,415144.0
143,Andaman-&-Nicobar-Islands,2024,1,744103,302,456306.0
153,Andaman-&-Nicobar-Islands,2024,2,744103,285,438830.0
163,Andaman-&-Nicobar-Islands,2024,3,744103,359,554559.0
173,Andaman-&-Nicobar-Islands,2024,4,744103,369,521509.0

## VALIDATE FINAL DATASET INTEGRITY ##

In [33]:
top_insurance_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6668 entries, 0 to 6667
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             6668 non-null   str
 1   year              6668 non-null   str
 2   quarter           6668 non-null   int64
 3   pincodes          6668 non-null   str
 4   insurance_count   6668 non-null   int64
 5   insurance_amount  6668 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 444.5 KB

In [34]:
top_insurance_pincodes_df['year'] = top_insurance_pincodes_df['year'].astype('int32')
top_insurance_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6668 entries, 0 to 6667
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             6668 non-null   str
 1   year              6668 non-null   int32
 2   quarter           6668 non-null   int64
 3   pincodes          6668 non-null   str
 4   insurance_count   6668 non-null   int64
 5   insurance_amount  6668 non-null   float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 392.4 KB

In [35]:
top_insurance_pincodes_df

,state,year,quarter,pincodes,insurance_count,insurance_amount
0,Andaman-&-Nicobar-Islands,2020,2,744301,3,565.0
1,Andaman-&-Nicobar-Islands,2020,2,744104,2,513.0
2,Andaman-&-Nicobar-Islands,2020,2,744101,1,282.0
3,Andaman-&-Nicobar-Islands,2020,3,744112,9,3432.0
4,Andaman-&-Nicobar-Islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,West-Bengal,2024,4,711101,713,750354.0
6664,West-Bengal,2024,4,700091,642,969634.0
6665,West-Bengal,2024,4,700150,627,761501.0
6666,West-Bengal,2024,4,700039,619,787836.0
6667,West-Bengal,2024,4,700156,574,888613.0

In [36]:
top_insurance_pincodes_df

,state,year,quarter,pincodes,insurance_count,insurance_amount
0,Andaman-&-Nicobar-Islands,2020,2,744301,3,565.0
1,Andaman-&-Nicobar-Islands,2020,2,744104,2,513.0
2,Andaman-&-Nicobar-Islands,2020,2,744101,1,282.0
3,Andaman-&-Nicobar-Islands,2020,3,744112,9,3432.0
4,Andaman-&-Nicobar-Islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,West-Bengal,2024,4,711101,713,750354.0
6664,West-Bengal,2024,4,700091,642,969634.0
6665,West-Bengal,2024,4,700150,627,761501.0
6666,West-Bengal,2024,4,700039,619,787836.0
6667,West-Bengal,2024,4,700156,574,888613.0

In [37]:
top_insurance_pincodes_df['pincodes'] = top_insurance_pincodes_df['pincodes'].str.strip().str.title()

In [38]:
top_insurance_pincodes_df['pincodes']

0       744301
1       744104
2       744101
3       744112
4       744105
         ...
6663    711101
6664    700091
6665    700150
6666    700039
6667    700156
Name: pincodes, Length: 6668, dtype: str

In [39]:
top_insurance_pincodes_df

,state,year,quarter,pincodes,insurance_count,insurance_amount
0,Andaman-&-Nicobar-Islands,2020,2,744301,3,565.0
1,Andaman-&-Nicobar-Islands,2020,2,744104,2,513.0
2,Andaman-&-Nicobar-Islands,2020,2,744101,1,282.0
3,Andaman-&-Nicobar-Islands,2020,3,744112,9,3432.0
4,Andaman-&-Nicobar-Islands,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,West-Bengal,2024,4,711101,713,750354.0
6664,West-Bengal,2024,4,700091,642,969634.0
6665,West-Bengal,2024,4,700150,627,761501.0
6666,West-Bengal,2024,4,700039,619,787836.0
6667,West-Bengal,2024,4,700156,574,888613.0

In [41]:
top_insurance_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6668 entries, 0 to 6667
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             6668 non-null   str
 1   year              6668 non-null   int32
 2   quarter           6668 non-null   int64
 3   pincodes          6668 non-null   str
 4   insurance_count   6668 non-null   int64
 5   insurance_amount  6668 non-null   float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 393.2 KB

In [42]:
top_insurance_pincodes_df['pincodes'].unique()

<ArrowStringArray>
['744301', '744104', '744101', '744112', '744105', '744206', '744107',
 '744103', '744302', '744211',
 ...
 '712223', '700078', '713102', '700036', '711202', '713101', '700014',
 '700052', '721301', '734001']
Length: 900, dtype: str

In [43]:
top_insurance_pincodes_df['pincodes'] = top_insurance_pincodes_df['pincodes'].astype('category')

In [44]:
top_insurance_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6668 entries, 0 to 6667
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             6668 non-null   str
 1   year              6668 non-null   int32
 2   quarter           6668 non-null   int64
 3   pincodes          6668 non-null   category
 4   insurance_count   6668 non-null   int64
 5   insurance_amount  6668 non-null   float64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 326.6 KB

## Create insurance_pincodes_top Table In Database ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS insurance_pincodes_top (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,    
        pincodes VARCHAR(255) NOT NULL,
        insurance_count BIGINT,
        insurance_amount BIGINT
    );
""")

cur.execute("SELECT to_regclass('public.insurance_pincodes_top')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'insurance_pincodes_top' created successfully")

Table exists in PostgreSQL: insurance_pincodes_top
Table 'insurance_pincodes_top' created successfully

## Inserting Data from Data Frame to Insurance_Pincodes_Top Table ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in top_insurance_pincodes_df.iterrows():
    cur.execute(
        """
        INSERT INTO insurance_pincodes_top (
            state,
            year,
            quarter,
            pincodes,
            insurance_count,
            insurance_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["pincodes"],
            row["insurance_count"],
            row["insurance_amount"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully