# Top Insurance Districts data analysis #

In [34]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\top\\insurance\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
clm={'state':[], 'year':[],'quarter':[],'districts':[], 'total_amount':[], 'total_count':[] }

for i in top_state_list:
    p_i=path+i+"\\"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"\\"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['districts']:
                districts = z['entityName']
                total_amount = z['metric']['amount']
                total_count = z['metric']['count']
                clm['districts'].append(districts)
                clm['total_amount'].append(total_amount)
                clm['total_count'].append(total_count)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

top_insurance_districts_df=pd.DataFrame(clm)

top_insurance_districts_df

,state,year,quarter,districts,total_amount,total_count
0,andaman-&-nicobar-islands,2020,2,nicobars,565.0,3
1,andaman-&-nicobar-islands,2020,2,south andaman,795.0,3
2,andaman-&-nicobar-islands,2020,3,south andaman,13651.0,35
3,andaman-&-nicobar-islands,2020,3,nicobars,1448.0,5
4,andaman-&-nicobar-islands,2020,3,north and middle andaman,281.0,1
...,...,...,...,...,...,...
5603,west-bengal,2024,4,paschim bardhaman,7005851.0,4945
5604,west-bengal,2024,4,paschim medinipur,5405054.0,4155
5605,west-bengal,2024,4,malda,4902098.0,4042
5606,west-bengal,2024,4,nadia,5031294.0,3807
5607,west-bengal,2024,4,purba bardhaman,4482879.0,3595

In [35]:
top_insurance_districts_df.shape

(5608, 6)

In [36]:
top_insurance_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         5608 non-null   str
 1   year          5608 non-null   str
 2   quarter       5608 non-null   int64
 3   districts     5608 non-null   str
 4   total_amount  5608 non-null   float64
 5   total_count   5608 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 386.5 KB

In [37]:
q2_andaman = top_insurance_districts_df[
    (top_insurance_districts_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (top_insurance_districts_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'districts', 'total_amount', 'total_count']])

    year  quarter                 districts  total_amount  total_count
0   2020        2                  nicobars         565.0            3
1   2020        2             south andaman         795.0            3
11  2021        2             south andaman      121104.0          105
12  2021        2  north and middle andaman       45311.0           28
13  2021        2                  nicobars       15089.0            4
23  2022        2             south andaman      633029.0          430
24  2022        2  north and middle andaman       90403.0           45
25  2022        2                  nicobars       56308.0           26
35  2023        2             south andaman     1060976.0          670
36  2023        2  north and middle andaman      109742.0           56
37  2023        2                  nicobars       62677.0           42
47  2024        2             south andaman     1513489.0          974
48  2024        2  north and middle andaman      164686.0           74
49  2024        2                  nicobars       66519.0           49

In [38]:
top_insurance_districts_df.describe()

           quarter  total_amount   total_count
count  5608.000000  5.608000e+03   5608.000000
mean      2.580777  2.661812e+06   1977.296897
std       1.092919  6.842624e+06   4742.819638
min       1.000000  3.200000e+01      1.000000
25%       2.000000  1.177565e+05    126.500000
50%       3.000000  8.024965e+05    709.000000
75%       4.000000  2.848404e+06   2146.250000
max       4.000000  1.592248e+08  96935.000000

In [39]:
top_insurance_districts_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [40]:
top_insurance_districts_df.isna().sum()

state           0
year            0
quarter         0
districts       0
total_amount    0
total_count     0
dtype: int64

In [41]:
top_insurance_districts_df['districts'].isna().sum()

np.int64(0)

In [42]:
top_insurance_districts_df['districts']

0                       nicobars
1                  south andaman
2                  south andaman
3                       nicobars
4       north and middle andaman
                  ...
5603           paschim bardhaman
5604           paschim medinipur
5605                       malda
5606                       nadia
5607             purba bardhaman
Name: districts, Length: 5608, dtype: str

In [43]:
top_insurance_districts_df[top_insurance_districts_df['districts'].isna()]

Empty DataFrame
Columns: [state, year, quarter, districts, total_amount, total_count]
Index: []

In [44]:
top_insurance_districts_df[top_insurance_districts_df['districts'].isna()]

Empty DataFrame
Columns: [state, year, quarter, districts, total_amount, total_count]
Index: []

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [45]:
top_insurance_districts_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [46]:
top_insurance_districts_df['state'].value_counts()

state
andhra-pradesh                        190
arunachal-pradesh                     190
assam                                 190
bihar                                 190
chhattisgarh                          190
delhi                                 190
gujarat                               190
haryana                               190
himachal-pradesh                      190
jammu-&-kashmir                       190
jharkhand                             190
karnataka                             190
kerala                                190
madhya-pradesh                        190
maharashtra                           190
manipur                               190
odisha                                190
punjab                                190
rajasthan                             190
tamil-nadu                            190
telangana                             190
uttar-pradesh                         190
uttarakhand                           190
west-bengal                           190
meghalaya                             185
nagaland                              182
tripura                               152
mizoram                               148
sikkim                                 79
puducherry                             76
andaman-&-nicobar-islands              57
dadra-&-nagar-haveli-&-daman-&-diu     57
goa                                    38
ladakh                                 38
chandigarh                             19
lakshadweep                            17
Name: count, dtype: int64

In [47]:
top_insurance_districts_df['state'] = top_insurance_districts_df['state'].str.strip().str.title()

In [48]:
top_insurance_districts_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Districts Column Unique Values ##

In [49]:
top_insurance_districts_df['districts'].unique()

<ArrowStringArray>
[                'nicobars',            'south andaman',
 'north and middle andaman',                  'nicobar',
            'visakhapatnam',                'anantapur',
                  'krishna',                 'chittoor',
                      'ysr',                   'guntur',
 ...
        'paschim bardhaman',                    'nadia',
          'purba medinipur',        'paschim medinipur',
                'darjiling',              'murshidabad',
               'koch bihar',                   'maldah',
          'purba bardhaman',                    'malda']
Length: 412, dtype: str

In [50]:
top_insurance_districts_df[top_insurance_districts_df['districts'] == 'nicobar']

,state,year,quarter,districts,total_amount,total_count
52,Andaman-&-Nicobar-Islands,2024,3,nicobar,68638.0,51
56,Andaman-&-Nicobar-Islands,2024,4,nicobar,136595.0,77

In [51]:
top_insurance_districts_df['districts'] = top_insurance_districts_df['districts'].replace('nicobar', 'nicobars')

In [52]:
top_insurance_districts_df[top_insurance_districts_df['districts'] == 'nicobars']

,state,year,quarter,districts,total_amount,total_count
0,Andaman-&-Nicobar-Islands,2020,2,nicobars,565.0,3
3,Andaman-&-Nicobar-Islands,2020,3,nicobars,1448.0,5
7,Andaman-&-Nicobar-Islands,2020,4,nicobars,2747.0,2
10,Andaman-&-Nicobar-Islands,2021,1,nicobars,13244.0,13
13,Andaman-&-Nicobar-Islands,2021,2,nicobars,15089.0,4
16,Andaman-&-Nicobar-Islands,2021,3,nicobars,30539.0,15
19,Andaman-&-Nicobar-Islands,2021,4,nicobars,73561.0,44
22,Andaman-&-Nicobar-Islands,2022,1,nicobars,63852.0,28
25,Andaman-&-Nicobar-Islands,2022,2,nicobars,56308.0,26
28,Andaman-&-Nicobar-Islands,2022,3,nicobars,85640.0,38
31,Andaman-&-Nicobar-Islands,2022,4,nicobars,102155.0,39
34,Andaman-&-Nicobar-Islands,2023,1,nicobars,88146.0,47
37,Andaman-&-Nicobar-Islands,2023,2,nicobars,62677.0,42
40,Andaman-&-Nicobar-Islands,2023,3,nicobars,65285.0,36
43,Andaman-&-Nicobar-Islands,2023,4,nicobars,96298.0,44
46,Andaman-&-Nicobar-Islands,2024,1,nicobars,77703.0,56
49,Andaman-&-Nicobar-Islands,2024,2,nicobars,66519.0,49
52,Andaman-&-Nicobar-Islands,2024,3,nicobars,68638.0,51
53,Andaman-&-Nicobar-Islands,2024,3,nicobars,2192.0,1
56,Andaman-&-Nicobar-Islands,2024,4,nicobars,136595.0,77

In [53]:
top_insurance_districts_df['districts'].unique()

<ArrowStringArray>
[                'nicobars',            'south andaman',
 'north and middle andaman',            'visakhapatnam',
                'anantapur',                  'krishna',
                 'chittoor',                      'ysr',
                   'guntur',            'east godavari',
 ...
        'paschim bardhaman',                    'nadia',
          'purba medinipur',        'paschim medinipur',
                'darjiling',              'murshidabad',
               'koch bihar',                   'maldah',
          'purba bardhaman',                    'malda']
Length: 411, dtype: str

## VALIDATE FINAL DATASET INTEGRITY ##

In [54]:
top_insurance_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         5608 non-null   str
 1   year          5608 non-null   str
 2   quarter       5608 non-null   int64
 3   districts     5608 non-null   str
 4   total_amount  5608 non-null   float64
 5   total_count   5608 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 387.2 KB

In [55]:
top_insurance_districts_df['year'] = top_insurance_districts_df['year'].astype('int32')
top_insurance_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         5608 non-null   str
 1   year          5608 non-null   int32
 2   quarter       5608 non-null   int64
 3   districts     5608 non-null   str
 4   total_amount  5608 non-null   float64
 5   total_count   5608 non-null   int64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 343.4 KB

In [56]:
top_insurance_districts_df

,state,year,quarter,districts,total_amount,total_count
0,Andaman-&-Nicobar-Islands,2020,2,nicobars,565.0,3
1,Andaman-&-Nicobar-Islands,2020,2,south andaman,795.0,3
2,Andaman-&-Nicobar-Islands,2020,3,south andaman,13651.0,35
3,Andaman-&-Nicobar-Islands,2020,3,nicobars,1448.0,5
4,Andaman-&-Nicobar-Islands,2020,3,north and middle andaman,281.0,1
...,...,...,...,...,...,...
5603,West-Bengal,2024,4,paschim bardhaman,7005851.0,4945
5604,West-Bengal,2024,4,paschim medinipur,5405054.0,4155
5605,West-Bengal,2024,4,malda,4902098.0,4042
5606,West-Bengal,2024,4,nadia,5031294.0,3807
5607,West-Bengal,2024,4,purba bardhaman,4482879.0,3595

In [57]:
top_insurance_districts_df['districts'] = top_insurance_districts_df['districts'].str.strip().str.title()

In [58]:
top_insurance_districts_df['districts']

0                       Nicobars
1                  South Andaman
2                  South Andaman
3                       Nicobars
4       North And Middle Andaman
                  ...
5603           Paschim Bardhaman
5604           Paschim Medinipur
5605                       Malda
5606                       Nadia
5607             Purba Bardhaman
Name: districts, Length: 5608, dtype: str

In [59]:
top_insurance_districts_df

,state,year,quarter,districts,total_amount,total_count
0,Andaman-&-Nicobar-Islands,2020,2,Nicobars,565.0,3
1,Andaman-&-Nicobar-Islands,2020,2,South Andaman,795.0,3
2,Andaman-&-Nicobar-Islands,2020,3,South Andaman,13651.0,35
3,Andaman-&-Nicobar-Islands,2020,3,Nicobars,1448.0,5
4,Andaman-&-Nicobar-Islands,2020,3,North And Middle Andaman,281.0,1
...,...,...,...,...,...,...
5603,West-Bengal,2024,4,Paschim Bardhaman,7005851.0,4945
5604,West-Bengal,2024,4,Paschim Medinipur,5405054.0,4155
5605,West-Bengal,2024,4,Malda,4902098.0,4042
5606,West-Bengal,2024,4,Nadia,5031294.0,3807
5607,West-Bengal,2024,4,Purba Bardhaman,4482879.0,3595

In [60]:
top_insurance_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         5608 non-null   str
 1   year          5608 non-null   int32
 2   quarter       5608 non-null   int64
 3   districts     5608 non-null   str
 4   total_amount  5608 non-null   float64
 5   total_count   5608 non-null   int64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 344.1 KB

In [61]:
top_insurance_districts_df['districts'].unique()

<ArrowStringArray>
[                'Nicobars',            'South Andaman',
 'North And Middle Andaman',            'Visakhapatnam',
                'Anantapur',                  'Krishna',
                 'Chittoor',                      'Ysr',
                   'Guntur',            'East Godavari',
 ...
        'Paschim Bardhaman',                    'Nadia',
          'Purba Medinipur',        'Paschim Medinipur',
                'Darjiling',              'Murshidabad',
               'Koch Bihar',                   'Maldah',
          'Purba Bardhaman',                    'Malda']
Length: 411, dtype: str

In [62]:
top_insurance_districts_df['districts'] = top_insurance_districts_df['districts'].astype('category')

In [63]:
top_insurance_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         5608 non-null   str
 1   year          5608 non-null   int32
 2   quarter       5608 non-null   int64
 3   districts     5608 non-null   category
 4   total_amount  5608 non-null   float64
 5   total_count   5608 non-null   int64
dtypes: category(1), float64(1), int32(1), int64(2), str(1)
memory usage: 269.5 KB

## Create Insurance_district_top Table In Database ##

In [64]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS insurance_districts_top (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,
        districts VARCHAR(255) NOT NULL,
        total_count BIGINT,
        total_amount NUMERIC(15, 2)
    );
""")

cur.execute("SELECT to_regclass('public.insurance_districts_top')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'insurance_districts_top' created successfully")

Table exists in PostgreSQL: insurance_districts_top
Table 'insurance_districts_top' created successfully

## Inserting Data from Data Frame to Insurance_district_Top Table ##

In [65]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in top_insurance_districts_df.iterrows():
    cur.execute(
        """
        INSERT INTO insurance_districts_top (
            state,
            year,
            quarter,
            districts,
            total_count,
            total_amount
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["districts"],
            row["total_count"],
            row["total_amount"],
        )
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully
Data inserted successfully