# Top User District data analysis #

In [34]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\top\\user\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
clm={'state':[], 'year':[],'quarter':[],'districts':[], 'registeredUsers':[] }

for i in top_state_list:
    p_i=path+i+"\\"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"\\"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['districts']:
                districts = z['name']
                registeredUsers=z['registeredUsers']
                clm['districts'].append(districts)
                clm['registeredUsers'].append(registeredUsers)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

top_users_districts_df=pd.DataFrame(clm)

top_users_districts_df

,state,year,quarter,districts,registeredUsers
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,west-bengal,2024,4,hooghly,1957356
8292,west-bengal,2024,4,nadia,1861738
8293,west-bengal,2024,4,purba medinipur,1717074
8294,west-bengal,2024,4,paschim medinipur,1522845
8295,west-bengal,2024,4,paschim bardhaman,1468252

In [35]:
top_users_districts_df.shape

(8296, 5)

In [36]:
top_users_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            8296 non-null   str
 1   year             8296 non-null   str
 2   quarter          8296 non-null   int64
 3   districts        8296 non-null   str
 4   registeredUsers  8296 non-null   int64
dtypes: int64(2), str(3)
memory usage: 507.2 KB

In [37]:
q2_andaman = top_users_districts_df[
    (top_users_districts_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (top_users_districts_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'districts', 'registeredUsers']])

    year  quarter                 districts  registeredUsers
3   2018        2             south andaman             8143
4   2018        2  north and middle andaman              911
5   2018        2                  nicobars              351
15  2019        2             south andaman            18621
16  2019        2  north and middle andaman             2417
17  2019        2                  nicobars              693
27  2020        2             south andaman            27626
28  2020        2  north and middle andaman             4100
29  2020        2                  nicobars              984
39  2021        2             south andaman            51903
40  2021        2  north and middle andaman             8493
41  2021        2                  nicobars             1699
51  2022        2             south andaman            66959
52  2022        2  north and middle andaman            11379
53  2022        2                  nicobars             2192
63  2023        2             south andaman            80112
64  2023        2  north and middle andaman            13600
65  2023        2                  nicobars             2617
75  2024        2             south andaman            93421
76  2024        2  north and middle andaman            16183
77  2024        2                  nicobars             3083

In [38]:
top_users_districts_df.describe()

           quarter  registeredUsers
count  8296.000000     8.296000e+03
mean      2.500964     7.052733e+05
std       1.118101     1.194705e+06
min       1.000000     1.680000e+02
25%       2.000000     6.236125e+04
50%       3.000000     3.301680e+05
75%       4.000000     9.005492e+05
max       4.000000     1.812748e+07

In [39]:
top_users_districts_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [40]:
top_users_districts_df.isna().sum()

state              0
year               0
quarter            0
districts          0
registeredUsers    0
dtype: int64

In [41]:
top_users_districts_df['districts'].isna().sum()

np.int64(0)

In [43]:
top_users_districts_df['districts']

0                  south andaman
1       north and middle andaman
2                       nicobars
3                  south andaman
4       north and middle andaman
                  ...
8291                     hooghly
8292                       nadia
8293             purba medinipur
8294           paschim medinipur
8295           paschim bardhaman
Name: districts, Length: 8296, dtype: str

In [44]:
top_users_districts_df[top_users_districts_df['districts'].isna()]

Empty DataFrame
Columns: [state, year, quarter, districts, registeredUsers]
Index: []

In [45]:
top_users_districts_df[top_users_districts_df['districts'].isna()]

Empty DataFrame
Columns: [state, year, quarter, districts, registeredUsers]
Index: []

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [46]:
top_users_districts_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [47]:
top_users_districts_df['state'].value_counts()

state
andhra-pradesh                        280
arunachal-pradesh                     280
assam                                 280
bihar                                 280
chhattisgarh                          280
delhi                                 280
gujarat                               280
haryana                               280
himachal-pradesh                      280
jammu-&-kashmir                       280
jharkhand                             280
karnataka                             280
kerala                                280
madhya-pradesh                        280
maharashtra                           280
manipur                               280
meghalaya                             280
nagaland                              280
odisha                                280
punjab                                280
rajasthan                             280
tamil-nadu                            280
telangana                             280
uttar-pradesh                         280
uttarakhand                           280
west-bengal                           280
mizoram                               228
tripura                               224
sikkim                                116
puducherry                            112
andaman-&-nicobar-islands              84
dadra-&-nagar-haveli-&-daman-&-diu     84
goa                                    56
ladakh                                 56
chandigarh                             28
lakshadweep                            28
Name: count, dtype: int64

In [48]:
top_users_districts_df['state'] = top_users_districts_df['state'].str.strip().str.title()

In [49]:
top_users_districts_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Districts Column Unique Values ##

In [50]:
top_users_districts_df['districts'].unique()

<ArrowStringArray>
[             'south andaman',   'north and middle andaman',
                   'nicobars',                    'nicobar',
              'visakhapatnam',              'east godavari',
                    'krishna',                     'guntur',
                   'chittoor',                  'anantapur',
 ...
                    'kolkata',                'murshidabad',
                    'hooghly', 'south twenty four parganas',
          'paschim bardhaman',                     'howrah',
                      'nadia',            'purba medinipur',
          'paschim medinipur',            'purba bardhaman']
Length: 348, dtype: str

In [51]:
top_users_districts_df[top_users_districts_df['districts'] == 'nicobar']

                        state  year  quarter districts  registeredUsers
80  Andaman-&-Nicobar-Islands  2024        3   nicobar             7495
83  Andaman-&-Nicobar-Islands  2024        4   nicobar             7698

In [52]:
top_users_districts_df['districts'] = top_users_districts_df['districts'].replace('nicobar', 'nicobars')

In [53]:
top_users_districts_df[top_users_districts_df['districts'] == 'nicobar']

Empty DataFrame
Columns: [state, year, quarter, districts, registeredUsers]
Index: []

In [54]:
top_users_districts_df[top_users_districts_df['districts'] == 'nicobars']

                        state  year  quarter districts  registeredUsers
2   Andaman-&-Nicobar-Islands  2018        1  nicobars              262
5   Andaman-&-Nicobar-Islands  2018        2  nicobars              351
8   Andaman-&-Nicobar-Islands  2018        3  nicobars              467
11  Andaman-&-Nicobar-Islands  2018        4  nicobars              536
14  Andaman-&-Nicobar-Islands  2019        1  nicobars              622
17  Andaman-&-Nicobar-Islands  2019        2  nicobars              693
20  Andaman-&-Nicobar-Islands  2019        3  nicobars              751
23  Andaman-&-Nicobar-Islands  2019        4  nicobars              803
26  Andaman-&-Nicobar-Islands  2020        1  nicobars              879
29  Andaman-&-Nicobar-Islands  2020        2  nicobars              984
32  Andaman-&-Nicobar-Islands  2020        3  nicobars             1147
35  Andaman-&-Nicobar-Islands  2020        4  nicobars             1412
38  Andaman-&-Nicobar-Islands  2021        1  nicobars             1573
41  Andaman-&-Nicobar-Islands  2021        2  nicobars             1699
44  Andaman-&-Nicobar-Islands  2021        3  nicobars             1846
47  Andaman-&-Nicobar-Islands  2021        4  nicobars             1971
50  Andaman-&-Nicobar-Islands  2022        1  nicobars             2081
53  Andaman-&-Nicobar-Islands  2022        2  nicobars             2192
56  Andaman-&-Nicobar-Islands  2022        3  nicobars             2300
59  Andaman-&-Nicobar-Islands  2022        4  nicobars             2389
62  Andaman-&-Nicobar-Islands  2023        1  nicobars             2491
65  Andaman-&-Nicobar-Islands  2023        2  nicobars             2617
68  Andaman-&-Nicobar-Islands  2023        3  nicobars             2734
71  Andaman-&-Nicobar-Islands  2023        4  nicobars             2817
74  Andaman-&-Nicobar-Islands  2024        1  nicobars             2965
77  Andaman-&-Nicobar-Islands  2024        2  nicobars             3083
80  Andaman-&-Nicobar-Islands  2024        3  nicobars             7495
83  Andaman-&-Nicobar-Islands  2024        4  nicobars             7698

In [55]:
top_users_districts_df['districts'].unique()

<ArrowStringArray>
[             'south andaman',   'north and middle andaman',
                   'nicobars',              'visakhapatnam',
              'east godavari',                    'krishna',
                     'guntur',                   'chittoor',
                  'anantapur',                    'kurnool',
 ...
                    'kolkata',                'murshidabad',
                    'hooghly', 'south twenty four parganas',
          'paschim bardhaman',                     'howrah',
                      'nadia',            'purba medinipur',
          'paschim medinipur',            'purba bardhaman']
Length: 347, dtype: str

## VALIDATE FINAL DATASET INTEGRITY ##

In [56]:
top_users_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            8296 non-null   str
 1   year             8296 non-null   str
 2   quarter          8296 non-null   int64
 3   districts        8296 non-null   str
 4   registeredUsers  8296 non-null   int64
dtypes: int64(2), str(3)
memory usage: 508.2 KB

In [57]:
top_users_districts_df['year'] = top_users_districts_df['year'].astype('int32')
top_users_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            8296 non-null   str
 1   year             8296 non-null   int32
 2   quarter          8296 non-null   int64
 3   districts        8296 non-null   str
 4   registeredUsers  8296 non-null   int64
dtypes: int32(1), int64(2), str(2)
memory usage: 443.4 KB

In [58]:
top_users_districts_df

,state,year,quarter,districts,registeredUsers
0,Andaman-&-Nicobar-Islands,2018,1,south andaman,5846
1,Andaman-&-Nicobar-Islands,2018,1,north and middle andaman,632
2,Andaman-&-Nicobar-Islands,2018,1,nicobars,262
3,Andaman-&-Nicobar-Islands,2018,2,south andaman,8143
4,Andaman-&-Nicobar-Islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,West-Bengal,2024,4,hooghly,1957356
8292,West-Bengal,2024,4,nadia,1861738
8293,West-Bengal,2024,4,purba medinipur,1717074
8294,West-Bengal,2024,4,paschim medinipur,1522845
8295,West-Bengal,2024,4,paschim bardhaman,1468252

In [59]:
top_users_districts_df

,state,year,quarter,districts,registeredUsers
0,Andaman-&-Nicobar-Islands,2018,1,south andaman,5846
1,Andaman-&-Nicobar-Islands,2018,1,north and middle andaman,632
2,Andaman-&-Nicobar-Islands,2018,1,nicobars,262
3,Andaman-&-Nicobar-Islands,2018,2,south andaman,8143
4,Andaman-&-Nicobar-Islands,2018,2,north and middle andaman,911
...,...,...,...,...,...
8291,West-Bengal,2024,4,hooghly,1957356
8292,West-Bengal,2024,4,nadia,1861738
8293,West-Bengal,2024,4,purba medinipur,1717074
8294,West-Bengal,2024,4,paschim medinipur,1522845
8295,West-Bengal,2024,4,paschim bardhaman,1468252

In [60]:
top_users_districts_df['districts'] = top_users_districts_df['districts'].str.strip().str.title()

In [61]:
top_users_districts_df['districts']

0                  South Andaman
1       North And Middle Andaman
2                       Nicobars
3                  South Andaman
4       North And Middle Andaman
                  ...
8291                     Hooghly
8292                       Nadia
8293             Purba Medinipur
8294           Paschim Medinipur
8295           Paschim Bardhaman
Name: districts, Length: 8296, dtype: str

In [62]:
top_users_districts_df

,state,year,quarter,districts,registeredUsers
0,Andaman-&-Nicobar-Islands,2018,1,South Andaman,5846
1,Andaman-&-Nicobar-Islands,2018,1,North And Middle Andaman,632
2,Andaman-&-Nicobar-Islands,2018,1,Nicobars,262
3,Andaman-&-Nicobar-Islands,2018,2,South Andaman,8143
4,Andaman-&-Nicobar-Islands,2018,2,North And Middle Andaman,911
...,...,...,...,...,...
8291,West-Bengal,2024,4,Hooghly,1957356
8292,West-Bengal,2024,4,Nadia,1861738
8293,West-Bengal,2024,4,Purba Medinipur,1717074
8294,West-Bengal,2024,4,Paschim Medinipur,1522845
8295,West-Bengal,2024,4,Paschim Bardhaman,1468252

In [63]:
top_users_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            8296 non-null   str
 1   year             8296 non-null   int32
 2   quarter          8296 non-null   int64
 3   districts        8296 non-null   str
 4   registeredUsers  8296 non-null   int64
dtypes: int32(1), int64(2), str(2)
memory usage: 444.4 KB

In [64]:
top_users_districts_df['districts'].unique()

<ArrowStringArray>
[             'South Andaman',   'North And Middle Andaman',
                   'Nicobars',              'Visakhapatnam',
              'East Godavari',                    'Krishna',
                     'Guntur',                   'Chittoor',
                  'Anantapur',                    'Kurnool',
 ...
                    'Kolkata',                'Murshidabad',
                    'Hooghly', 'South Twenty Four Parganas',
          'Paschim Bardhaman',                     'Howrah',
                      'Nadia',            'Purba Medinipur',
          'Paschim Medinipur',            'Purba Bardhaman']
Length: 347, dtype: str

In [65]:
top_users_districts_df['districts'] = top_users_districts_df['districts'].astype('category')

In [66]:
top_users_districts_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            8296 non-null   str
 1   year             8296 non-null   int32
 2   quarter          8296 non-null   int64
 3   districts        8296 non-null   category
 4   registeredUsers  8296 non-null   int64
dtypes: category(1), int32(1), int64(2), str(1)
memory usage: 329.4 KB

## Create users_district_top Table In Database ##

In [67]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS users_districts_top (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,
        districts VARCHAR(255) NOT NULL,
        registeredUsers BIGINT
    );
""")

cur.execute("SELECT to_regclass('public.users_districts_top')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'users_districts_top' created successfully")

Table exists in PostgreSQL: users_districts_top
Table 'users_districts_top' created successfully

## Inserting Data from Data Frame to Users_district_Top Table ##

In [68]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="HareKrishna@143",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in top_users_districts_df.iterrows():
    cur.execute(
        """
        INSERT INTO users_districts_top (
            state,
            year,
            quarter,
            districts,
            registeredUsers
        )
        VALUES (%s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["districts"],
            row["registeredUsers"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully