# Top Users Pincodes data analysis #

In [1]:
import pandas as pd
import json
import os

#This is to direct the path to get the data as states
path="D:\\GITHUB REPO\\pulse\\data\\top\\user\\country\\india\\state\\"
top_state_list=os.listdir(path)
top_state_list
clm={'state':[], 'year':[],'quarter':[],'pincodes':[], 'registeredUsers':[] }

for i in top_state_list:
    p_i=path+i+"\\"
    top_yr=os.listdir(p_i)
    for j in top_yr:
        p_j=p_i+j+"\\"
        top_yr_list=os.listdir(p_j)
        for k in top_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['pincodes']:
                pincodes = z['name']
                registeredUsers=z['registeredUsers']
                clm['pincodes'].append(pincodes)
                clm['registeredUsers'].append(registeredUsers)
                clm['state'].append(i)
                clm['year'].append(j)
                clm['quarter'].append(int(k.strip('.json')))

top_users_pincodes_df=pd.DataFrame(clm)

top_users_pincodes_df

                          state  year  quarter pincodes  registeredUsers
0     andaman-&-nicobar-islands  2018        1   744103             1608
1     andaman-&-nicobar-islands  2018        1   744101             1108
2     andaman-&-nicobar-islands  2018        1   744105             1075
3     andaman-&-nicobar-islands  2018        1   744102             1006
4     andaman-&-nicobar-islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                west-bengal  2024        4   733134           169596
9996                west-bengal  2024        4   700059           169448
9997                west-bengal  2024        4   711302           146034
9998                west-bengal  2024        4   700150           142151
9999                west-bengal  2024        4   711106           142077

[10000 rows x 5 columns]

In [4]:
top_users_pincodes_df.shape

(10000, 5)

In [5]:
top_users_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            10000 non-null  str
 1   year             10000 non-null  str
 2   quarter          10000 non-null  int64
 3   pincodes         10000 non-null  str
 4   registeredUsers  10000 non-null  int64
dtypes: int64(2), str(3)
memory usage: 588.1 KB

In [6]:
q2_andaman = top_users_pincodes_df[
    (top_users_pincodes_df['state'].str.lower() == 'andaman-&-nicobar-islands') &
    (top_users_pincodes_df['quarter'] == 2)
]
print(q2_andaman[['year', 'quarter', 'pincodes', 'registeredUsers']])

     year  quarter pincodes  registeredUsers
10   2018        2   744103             2188
11   2018        2   744101             1521
12   2018        2   744105             1492
13   2018        2   744102             1419
14   2018        2   744104              396
..    ...      ...      ...              ...
255  2024        2   744107             5184
256  2024        2   744104             4570
257  2024        2   744112             3761
258  2024        2   744211             3409
259  2024        2   744205             3090

[70 rows x 4 columns]

In [7]:
top_users_pincodes_df.describe()

           quarter  registeredUsers
count  10000.00000     1.000000e+04
mean       2.50040     1.030956e+05
std        1.11809     1.300479e+05
min        1.00000     1.000000e+00
25%        2.00000     1.376800e+04
50%        3.00000     4.635050e+04
75%        4.00000     1.475262e+05
max        4.00000     1.021560e+06

In [8]:
top_users_pincodes_df.duplicated().sum()

np.int64(0)

## CHECKING NAN ACCROSS ALL COLUMNS ##

In [9]:
top_users_pincodes_df.isna().sum()

state              0
year               0
quarter            0
pincodes           0
registeredUsers    0
dtype: int64

In [10]:
top_users_pincodes_df['pincodes'].isna().sum()

np.int64(0)

In [11]:
top_users_pincodes_df['pincodes']

0       744103
1       744101
2       744105
3       744102
4       744104
         ...
9995    733134
9996    700059
9997    711302
9998    700150
9999    711106
Name: pincodes, Length: 10000, dtype: str

In [12]:
top_users_pincodes_df[top_users_pincodes_df['pincodes'].isna()]

Empty DataFrame
Columns: [state, year, quarter, pincodes, registeredUsers]
Index: []

In [13]:
top_users_pincodes_df[top_users_pincodes_df['pincodes'].isna()]

Empty DataFrame
Columns: [state, year, quarter, pincodes, registeredUsers]
Index: []

## CHECKING STATE COLUMN UNIQUE VALUES ##

In [14]:
top_users_pincodes_df['state'].unique()

<ArrowStringArray>
[         'andaman-&-nicobar-islands',                     'andhra-pradesh',
                  'arunachal-pradesh',                              'assam',
                              'bihar',                         'chandigarh',
                       'chhattisgarh', 'dadra-&-nagar-haveli-&-daman-&-diu',
                              'delhi',                                'goa',
                            'gujarat',                            'haryana',
                   'himachal-pradesh',                    'jammu-&-kashmir',
                          'jharkhand',                          'karnataka',
                             'kerala',                             'ladakh',
                        'lakshadweep',                     'madhya-pradesh',
                        'maharashtra',                            'manipur',
                          'meghalaya',                            'mizoram',
                           'nagaland',                             'odisha',
                         'puducherry',                             'punjab',
                          'rajasthan',                             'sikkim',
                         'tamil-nadu',                          'telangana',
                            'tripura',                      'uttar-pradesh',
                        'uttarakhand',                        'west-bengal']
Length: 36, dtype: str

In [15]:
top_users_pincodes_df['state'].value_counts()

state
andaman-&-nicobar-islands             280
andhra-pradesh                        280
arunachal-pradesh                     280
assam                                 280
bihar                                 280
chandigarh                            280
chhattisgarh                          280
delhi                                 280
goa                                   280
gujarat                               280
haryana                               280
himachal-pradesh                      280
jammu-&-kashmir                       280
jharkhand                             280
karnataka                             280
kerala                                280
ladakh                                280
madhya-pradesh                        280
maharashtra                           280
manipur                               280
meghalaya                             280
mizoram                               280
nagaland                              280
odisha                                280
puducherry                            280
punjab                                280
rajasthan                             280
sikkim                                280
tamil-nadu                            280
telangana                             280
tripura                               280
uttar-pradesh                         280
uttarakhand                           280
west-bengal                           280
dadra-&-nagar-haveli-&-daman-&-diu    254
lakshadweep                           226
Name: count, dtype: int64

In [16]:
top_users_pincodes_df['state'] = top_users_pincodes_df['state'].str.strip().str.title()

In [17]:
top_users_pincodes_df['state'].unique()

<ArrowStringArray>
[         'Andaman-&-Nicobar-Islands',                     'Andhra-Pradesh',
                  'Arunachal-Pradesh',                              'Assam',
                              'Bihar',                         'Chandigarh',
                       'Chhattisgarh', 'Dadra-&-Nagar-Haveli-&-Daman-&-Diu',
                              'Delhi',                                'Goa',
                            'Gujarat',                            'Haryana',
                   'Himachal-Pradesh',                    'Jammu-&-Kashmir',
                          'Jharkhand',                          'Karnataka',
                             'Kerala',                             'Ladakh',
                        'Lakshadweep',                     'Madhya-Pradesh',
                        'Maharashtra',                            'Manipur',
                          'Meghalaya',                            'Mizoram',
                           'Nagaland',                             'Odisha',
                         'Puducherry',                             'Punjab',
                          'Rajasthan',                             'Sikkim',
                         'Tamil-Nadu',                          'Telangana',
                            'Tripura',                      'Uttar-Pradesh',
                        'Uttarakhand',                        'West-Bengal']
Length: 36, dtype: str

## CHECKING Districts Column Unique Values ##

In [18]:
top_users_pincodes_df['pincodes'].unique()

<ArrowStringArray>
['744103', '744101', '744105', '744102', '744104', '744202', '744112',
 '744301', '744107', '744211',
 ...
 '700015', '700021', '742304', '700150', '734006', '721301', '734001',
 '733134', '711302', '711106']
Length: 515, dtype: str

In [19]:
top_users_pincodes_df[top_users_pincodes_df['pincodes'] == '744103']

                         state  year  quarter pincodes  registeredUsers
0    Andaman-&-Nicobar-Islands  2018        1   744103             1608
10   Andaman-&-Nicobar-Islands  2018        2   744103             2188
20   Andaman-&-Nicobar-Islands  2018        3   744103             2741
30   Andaman-&-Nicobar-Islands  2018        4   744103             3373
40   Andaman-&-Nicobar-Islands  2019        1   744103             4136
50   Andaman-&-Nicobar-Islands  2019        2   744103             4748
60   Andaman-&-Nicobar-Islands  2019        3   744103             5218
70   Andaman-&-Nicobar-Islands  2019        4   744103             5637
80   Andaman-&-Nicobar-Islands  2020        1   744103             6108
90   Andaman-&-Nicobar-Islands  2020        2   744103             6804
100  Andaman-&-Nicobar-Islands  2020        3   744103             8318
110  Andaman-&-Nicobar-Islands  2020        4   744103            10408
120  Andaman-&-Nicobar-Islands  2021        1   744103            11416
130  Andaman-&-Nicobar-Islands  2021        2   744103            12268
140  Andaman-&-Nicobar-Islands  2021        3   744103            13198
150  Andaman-&-Nicobar-Islands  2021        4   744103            14127
160  Andaman-&-Nicobar-Islands  2022        1   744103            15011
170  Andaman-&-Nicobar-Islands  2022        2   744103            15799
180  Andaman-&-Nicobar-Islands  2022        3   744103            16666
190  Andaman-&-Nicobar-Islands  2022        4   744103            17406
200  Andaman-&-Nicobar-Islands  2023        1   744103            18209
210  Andaman-&-Nicobar-Islands  2023        2   744103            18944
220  Andaman-&-Nicobar-Islands  2023        3   744103            19673
230  Andaman-&-Nicobar-Islands  2023        4   744103            20431
240  Andaman-&-Nicobar-Islands  2024        1   744103            21242
250  Andaman-&-Nicobar-Islands  2024        2   744103            22049
260  Andaman-&-Nicobar-Islands  2024        3   744103            42228
270  Andaman-&-Nicobar-Islands  2024        4   744103            43485

## VALIDATE FINAL DATASET INTEGRITY ##

In [20]:
top_users_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            10000 non-null  str
 1   year             10000 non-null  str
 2   quarter          10000 non-null  int64
 3   pincodes         10000 non-null  str
 4   registeredUsers  10000 non-null  int64
dtypes: int64(2), str(3)
memory usage: 589.4 KB

In [21]:
top_users_pincodes_df['year'] = top_users_pincodes_df['year'].astype('int32')
top_users_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            10000 non-null  str
 1   year             10000 non-null  int32
 2   quarter          10000 non-null  int64
 3   pincodes         10000 non-null  str
 4   registeredUsers  10000 non-null  int64
dtypes: int32(1), int64(2), str(2)
memory usage: 511.2 KB

In [22]:
top_users_pincodes_df

                          state  year  quarter pincodes  registeredUsers
0     Andaman-&-Nicobar-Islands  2018        1   744103             1608
1     Andaman-&-Nicobar-Islands  2018        1   744101             1108
2     Andaman-&-Nicobar-Islands  2018        1   744105             1075
3     Andaman-&-Nicobar-Islands  2018        1   744102             1006
4     Andaman-&-Nicobar-Islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                West-Bengal  2024        4   733134           169596
9996                West-Bengal  2024        4   700059           169448
9997                West-Bengal  2024        4   711302           146034
9998                West-Bengal  2024        4   700150           142151
9999                West-Bengal  2024        4   711106           142077

[10000 rows x 5 columns]

In [23]:
top_users_pincodes_df

                          state  year  quarter pincodes  registeredUsers
0     Andaman-&-Nicobar-Islands  2018        1   744103             1608
1     Andaman-&-Nicobar-Islands  2018        1   744101             1108
2     Andaman-&-Nicobar-Islands  2018        1   744105             1075
3     Andaman-&-Nicobar-Islands  2018        1   744102             1006
4     Andaman-&-Nicobar-Islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                West-Bengal  2024        4   733134           169596
9996                West-Bengal  2024        4   700059           169448
9997                West-Bengal  2024        4   711302           146034
9998                West-Bengal  2024        4   700150           142151
9999                West-Bengal  2024        4   711106           142077

[10000 rows x 5 columns]

In [24]:
top_users_pincodes_df['pincodes'] = top_users_pincodes_df['pincodes'].str.strip().str.title()

In [25]:
top_users_pincodes_df['pincodes']

0       744103
1       744101
2       744105
3       744102
4       744104
         ...
9995    733134
9996    700059
9997    711302
9998    700150
9999    711106
Name: pincodes, Length: 10000, dtype: str

In [26]:
top_users_pincodes_df

                          state  year  quarter pincodes  registeredUsers
0     Andaman-&-Nicobar-Islands  2018        1   744103             1608
1     Andaman-&-Nicobar-Islands  2018        1   744101             1108
2     Andaman-&-Nicobar-Islands  2018        1   744105             1075
3     Andaman-&-Nicobar-Islands  2018        1   744102             1006
4     Andaman-&-Nicobar-Islands  2018        1   744104              272
...                         ...   ...      ...      ...              ...
9995                West-Bengal  2024        4   733134           169596
9996                West-Bengal  2024        4   700059           169448
9997                West-Bengal  2024        4   711302           146034
9998                West-Bengal  2024        4   700150           142151
9999                West-Bengal  2024        4   711106           142077

[10000 rows x 5 columns]

In [27]:
top_users_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            10000 non-null  str
 1   year             10000 non-null  int32
 2   quarter          10000 non-null  int64
 3   pincodes         10000 non-null  str
 4   registeredUsers  10000 non-null  int64
dtypes: int32(1), int64(2), str(2)
memory usage: 512.5 KB

In [29]:
top_users_pincodes_df['pincodes'].unique()

<ArrowStringArray>
['744103', '744101', '744105', '744102', '744104', '744202', '744112',
 '744301', '744107', '744211',
 ...
 '700015', '700021', '742304', '700150', '734006', '721301', '734001',
 '733134', '711302', '711106']
Length: 515, dtype: str

In [28]:
top_users_pincodes_df['pincodes'] = top_users_pincodes_df['pincodes'].astype('category')

In [29]:
top_users_pincodes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   state            10000 non-null  str
 1   year             10000 non-null  int32
 2   quarter          10000 non-null  int64
 3   pincodes         10000 non-null  category
 4   registeredUsers  10000 non-null  int64
dtypes: category(1), int32(1), int64(2), str(1)
memory usage: 401.2 KB

## Create users_pincodes_top Table In Database ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = True
cur = conn.cursor()

cur.execute("""
    CREATE TABLE IF NOT EXISTS users_pincodes_top (
        id SERIAL PRIMARY KEY,
        state VARCHAR(255) NOT NULL,
        year INTEGER NOT NULL,
        quarter INTEGER NOT NULL,
        pincodes VARCHAR(255) NOT NULL,
        registeredUsers BIGINT
    );
""")

cur.execute("SELECT to_regclass('public.users_pincodes_top')")
print("Table exists in PostgreSQL:", cur.fetchone()[0])

conn.commit()
cur.close()
conn.close()
print("Table 'users_pincodes_top' created successfully")

Table exists in PostgreSQL: users_pincodes_top
Table 'users_pincodes_top' created successfully

## Inserting Data from Data Frame to Users_pincodes_Top Table ##

In [ ]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="smart_pay",
    user="postgres",
    password="",
)
conn.autocommit = False
cur = conn.cursor()

for _, row in top_users_pincodes_df.iterrows():
    cur.execute(
        """
        INSERT INTO users_pincodes_top (
            state,
            year,
            quarter,
            pincodes,
            registeredUsers
        )
        VALUES (%s, %s, %s, %s, %s)
        """,
        (
            row["state"],
            row["year"],
            row["quarter"],
            row["pincodes"],
            row["registeredUsers"],
        ),
    )

conn.commit()
cur.close()
conn.close()
print("Data inserted successfully")

Data inserted successfully